### ISSUE TITLE
Queue entry id in the how message?

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#101]
Hi mxcubers,

I am refining the sending of the ho messages to the web client, right now I only forward the message itself (i.e. *centringSuccesfull*, *collectStarted*, ...). I was wondering if there is any method/whatever to see who is the queue entry that has sent a given message (without changing the ho).

I see that there there is the *get_current_entry* method but it only works during the execution of such entry.

thanks for any hint,

**Comment by mguijarr** [comment]
As we don't want to change hardware objects, we can try some kind of Python (black?) magic to extract the queue entry object from the stack frames in the event receiver callback in `signals.py`. The following could give us the `queue_entry` object (well, *maybe* - untested code):

```python
  import inspect
  
  stack = []
  frame = None
  try:
    stack = inspect.stack()
    while stack:
      frame = stack.pop()[0]
      if 'queue_entry' in frame.f_code.co_filename:
        try:
          queue_entry = frame.f_locals['self']
        except AttributeError:
          pass
        else:
          print 'called from this queue_entry:', queue_entry
  finally:
    del frame
    del stack
```

@meguiraun : can you test that ?

**Comment by meguiraun** [comment]
I will try to understand your magic first, and then test...
I was thinking on keeping track of the last entry sent to execution in the *routes.Queue*...

**Comment by mguijarr** [comment]
It's probably much simpler to do like you thought, in fact I may not have understood what you're really trying to achieve... Up to you. Tell me how it goes :)

**Comment by meguiraun** [comment]
done creating a variable in *routes.Queue* and accessing *from routes.signals* (in holds the last entry id sent to execution). Thanks for the magic anyway
