### ISSUE TITLE
Can not authenticate after period of inactivity

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1032]
At Max IV we noticed that in some cases it is not possible to authenticate. After entering valid credentials, the MXCuBE app stays stuck on the authentication screen with the loading loop icon in the "Sign in" button. This seems to happen after signing in successfully once followed by a period of inactivity.

**Comment by fabcor-maxiv** [comment]
We figured out that we could work around the issue by deleting the SQLite user database.

After trial and error we found a relatively reliable way to reproduce the issue:

* stop the server
* delete the user SQLite database
* start the server 
* authenticate successfully
* delete cookies (maybe not necessary)
* close the browser tab
* wait (at least 1 minute or maybe more?)
* try to authenticate again

**Comment by fabcor-maxiv** [comment]
After investigation we identified that the issue is triggered by either of these 2 function calls:

```
            self.update_operator(new_login=True)
            self.update_active_users()
```
https://github.com/mxcube/mxcubeweb/blob/a89e219ea5cf60e193d6e6b95c31651e08a41a33/mxcube3/core/components/user/usermanager.py#L183-L184

Any of these 2 function calls seem to trigger the issue.

And after further investigations, we identified that both of these functions contain similar code that deactivate the newly created user session:

https://github.com/mxcube/mxcubeweb/blob/a89e219ea5cf60e193d6e6b95c31651e08a41a33/mxcube3/core/components/user/usermanager.py#L100C1-L111C67

https://github.com/mxcube/mxcubeweb/blob/a89e219ea5cf60e193d6e6b95c31651e08a41a33/mxcube3/core/components/user/usermanager.py#L81C1-L92C67

```
            if (
                _u.active
                and _u.last_request_timestamp
                and (
                    datetime.datetime.now() - _u.last_request_timestamp
                ).total_seconds()
                > 60
            ):
                logging.getLogger("HWR.MX3").info(
                    f"Logged out inactive user {_u.username}"
                )
                self.app.server.user_datastore.deactivate_user(_u)
```

**Comment by marcus-oscarsson** [comment]
I tried to duplicate the issue with steps provided above, but I could still login.

The snippet above in `update_operator` is indeed a duplication of the logic in `update_active_users` and can simply be removed. If done, however, I believe that  `self.update_active_users() `needs to be moved so that its called before `update_operator`.

The session should be invalidated after more than 1 minutes inactivity that is the intended function. However that you can't sign-in again is strange. Its strange that you mention that loading button is "busy", it seems to indicate that something is blocking ? Can you find out where in the `login` function you are stuck, i.e by setting a breakpoint at the top of `login` ?

**Comment by fabcor-maxiv** [comment]
As an additional data point, the bug occurs when the front-end app enters this condition:

https://github.com/mxcube/mxcubeweb/blob/a89e219ea5cf60e193d6e6b95c31651e08a41a33/ui/src/actions/login.js#L152

**Comment by marcus-oscarsson** [comment]
Hm, but what does the server do at this point, there is a call to `select_proposal` just before. We are not using the later call because we still login directly with proposals, maybe thats why we don't have the issue ?,  do you get to the `select_proposal` logic ?

**Comment by fabcor-maxiv** [comment]
I have a working but incomplete fix here:

https://github.com/fabcor-maxiv/mxcubeweb/commit/075eb1b10888c8e9d934551a7c42b4bab1ddc215


> I tried to duplicate the issue with steps provided above, but I could still login.

Oh... There might be some other factor playing a role in this issue that we have not managed to identify yet.


> The session should be invalidated after more than 1 minutes inactivity that is the intended function.

Yes, agreed.


> Its strange that you mention that loading button is "busy", it seems to indicate that something is blocking ?

As far as I could understand what happens is that the back-end tells the front-end that the authentication was successful. Then the front-end asks the back-end for the user info, to which the back-end now answers that the user is not signed in. And indeed this is what seems to happen on the back end, a new valid user session is created when the user successfully enters the credentials. But this newly created user session is deleted when retrieving the user info. So the front-end is stuck in a somewhat inconsistent state.

**Comment by fabcor-maxiv** [comment]
> We are not using the later call because we still login directly with proposals, maybe thats why we don't have the issue ?

It could be. We do not authenticate with proposal. Login type is "user".



> do you get to the `select_proposal` logic ?

After a successful authentication, yes.

**Comment by marcus-oscarsson** [comment]
Hm, I see. Could you try to move `self.update_active_users()` to the top of `login` just above the creation of the user. I might see a potential issue there, its worth a try.

**Comment by fabcor-maxiv** [comment]
According to the unit tests introduced in these two pull requests:

* https://github.com/mxcube/mxcubeweb/pull/1036
* https://github.com/mxcube/mxcubeweb/pull/1044

... this is now solved. Probably the fix was introduced in one of these two commits:

* https://github.com/mxcube/mxcubeweb/commit/54704b9bcdd7b5759500a089aa1e328010e0c87c
* https://github.com/mxcube/mxcubeweb/commit/942115ad9374a3825dbd5492fe0bb71630348a3b
