### ISSUE TITLE
No password check in user-based authentication

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1045]
@marcus-oscarsson @elmjag @meguiraun 

I am now looking closer at user-based authentication (I had started with the default which is proposal-based), and it seems like there is no actual authentication step in user-based authentication.

This is what is currently on `develop` and the `password` variable does not seem to be used at all:

https://github.com/mxcube/mxcubeweb/blob/ae73f6995adceaaa3fab3d61d55492365af3033f/mxcube3/core/components/lims.py#L200-L236

It seems like there was code doing password check that was removed two weeks ago in this commit:

https://github.com/mxcube/mxcubeweb/commit/f2b58d655c6fe9af12a5fcc9cb12700b09e9a651#diff-251e239e9087b0366b928d2d56b21f6aef11f85f36700f484d0af1470e5f40abL200-L205

But this piece of code was not specific to user-based authentication. And I assume there might have been a good reason to remove it (maybe it was in the wrong place).

Maybe I am missing something... If not, I wonder what would now be the best way forward to reinstate password check in user-based authentication scenario.

**Comment by marcus-oscarsson** [comment]
The code that was removed in https://github.com/mxcube/mxcubeweb/commit/f2b58d655c6fe9af12a5fcc9cb12700b09e9a651#diff-251e239e9087b0366b928d2d56b21f6aef11f85f36700f484d0af1470e5f40abL200-L205 is related to the now deprecated REST ISPyB client, it should not have authenticated the user more than towards the REST service.

The SOAP ISPyB client however comes with the option to also use LDAP, https://github.com/mxcube/mxcubecore/blob/802ab2fcd5dd725b07e193774fddec9ac7bcc654/mxcubecore/HardwareObjects/ISPyBClient.py#L661

I think maybe the same call should probably be used for the "user based" login right ?

Marcus

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson Thanks for the info. I do not know anything about REST ISPyB and its deprecation. I have some catch up to do. Is there something I can read on this? I will also ask about this here internally and eventually come back to you with follow-up questions if any. Thanks

**Comment by marcus-oscarsson** [comment]
@fabcor Its actually a fairly recent change, the deprecation of IPSyB REST, so its not yet very documented. However the guys working with ISPyB can probably tell you more. In short ISPyB REST was the original attempt to replace the SOAP services with REST, however it really never gained momentum. Much later, a few months ago, PyISPyB was created. PyISPyB replaces the old REST services. However this project have somehow also been put on hold infavor for ICAT. I'm sure the ISPyB guys can fill you in.

The important bit for us to know is maybe that in MXCuBE we make very little use of this "original" REST client, it was only used to fetch direct links to certain results (for user convenience) which was not possible with the SOAP services. However we removed the REST client as its no longer developed and to be honest we prefer to simply have on kind of ISPyB client :)

Id recommend just moving the login call of the SOAP client, If you were using the REST client for authentication which one of course could. It should do the same thing in that case
