### ISSUE TITLE
Fix and automate Sphinx-based documentation in `/docs/`

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1053]
It would be nice to have documentation automatically published somewhere.

We have the basis for Sphinx-based documentation in `/docs/`. We could work on fixing this (it should be relatively straightforward). And then we could work on getting the GitHub workflows to automatically publish on *GitHub Pages*.

**Comment by marcus-oscarsson** [comment]
That would be awesome  :)

**Comment by fabcor-maxiv** [comment]
I had already looked at it a bit the other day when working on https://github.com/mxcube/mxcubeweb/pull/1044.

What I noticed is that the current documentation does not compile as is, it references Python import packages that doe not seem to exist anymore, probably it is from a time before a large refactoring. Anyway this was apparently about documenting the Flask routes (the REST endpoints for the front-end). But if I understood correctly we now have some automatically generated documentation for the REST endpoints (something OpenAPI based, I think?).

So we could probably remove these old ReStructuredText directives for auto-documenting the Flask routes (`.. autoflask::`) , and replace those with a link to the OpenAPI auto-generated doc.

**Comment by fabcor-maxiv** [comment]
Work has begun: https://github.com/mxcube/mxcubeweb/compare/develop...fabcor-maxiv:mxcubeweb:fix-docs

**Comment by marcus-oscarsson** [comment]
Very nice :)

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson Should it be deployed on GitHub pages or somewhere else? I am thinking maybe it would be comfortable to use [*readthedocs*](https://readthedocs.com/) to host the Sphinx-built documentation. In particular because it gives us preview built doc pages for each pull request. But if for example it is too inconvenient to set this up right now, we can focus on GitHub pages deployment only for now.

In any case, I guess you will need to do the initial setting, because I do not have the permissions. For example for [GitHub pages with a actions workflow](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow).

**Comment by marcus-oscarsson** [comment]
reathedocs sounds nice to me, have not used it int sometime, put I guess one can upload from an action ?

**Comment by marcus-oscarsson** [comment]
github pages are already on the gh-pages branch if thats what you need ?

**Comment by marcus-oscarsson** [comment]
https://github.com/mxcube/mxcubeweb/tree/gh-pages

**Comment by fabcor-maxiv** [comment]
Ah... I had not seen that GitHub Pages were already enabled for mxcubeweb. I will see if I can get the GitHub Actions Workflow to build and deploy automatically. Thanks :)

For read the docs it is necessary to create an account with them and register the GitHub repository in their web interface. Then in the `mxcubeweb` git repository itself we need to add a [`readthedocs.yaml` file](https://docs.readthedocs.io/en/stable/config-file/index.html). As far as I can recall that's it (but that was also a while ago since I last worked with this). There should be no need for GitHub actions workflow.

**Comment by marcus-oscarsson** [comment]
Cool, thanks alot, it will be super nice

**Comment by fabcor-maxiv** [comment]
Some temporary preview here: https://fabcor-maxiv.github.io/mxcubeweb/

**Comment by marcus-oscarsson** [comment]
Nice, well done ! :) :+1:

**Comment by rhfogh** [comment]
Very nice work.

Not sure where I should put comments, so I put them here:

- Front page: The list of members should be up to date. The Australian Synchrotron at least seems to be missing.

- Reporting bugs (in Contributing Guidelines) looks good, but I have never seen anyone report a bug that way. Still, let us keep it.

- Contributing code needs to be revisited, as it does not reflect current practices:
    - When making a PR code should not be merged, it should be rebased, where possible.
    - Commits should not be to master, but to develop
    - The responsibility for merging is not with the last reviewer, but with the person presenting the PR (if no one else does it). We are not really relying on pre-specified reviewers.
    - We are not using Travis any more, are we?

- The links to videos from the MXCuBE3 page are 'not found'. Maybe they are not there yet?
- Is the docker linked to up to date?

The installation guide looks really good. I shall try it out ASAP.

**Comment by marcus-oscarsson** [comment]
@rhfogh: Thanks for the feedback. So what @fabcor-maxiv did for the moment was to automate the build of the documentation but the documentation is still the one we had since before. 

Its true the the contributing guidelines needs to be updated, its work in progress. The other bits probably needs to be brushed up as well, but that needs to come in a second phase.

**Comment by fabcor-maxiv** [comment]
@rhfogh as @marcus-oscarsson already mentioned, this is mostly about reviving the Sphinx documentation. The content itself should be tackled in a separate effort. @rhfogh I encourage you to open a new issue ticket with these comments, that would be great.

**Comment by rhfogh** [comment]
No need to make an issue of it - Marcus has already dealt with all of it (Thanks @marcus-oscarsson )

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson 

Do you think you can help fix the settings for the GitHub Pages?

See this workflow run for example: https://github.com/mxcube/mxcubeweb/actions/runs/6335979596

> Branch "develop" is not allowed to deploy to github-pages due to environment protection rules.

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson See message above. Some GitHub settings are missing for deployment to GitHub pages

Another recent case:

![image](https://github.com/mxcube/mxcubeweb/assets/140523662/e0a12bba-4139-409e-ab95-155a4d32f9c2)

https://github.com/mxcube/mxcubeweb/actions/runs/6584304110
