### ISSUE TITLE
Preparation for October 2023 code camp 

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1054]
To gather all questions/issues regarding the preparation of the codecamp, for instance question regarding installation.

**Comment by mattclarke** [comment]
I'm going through https://github.com/mxcube/mxcubeweb/wiki and I've got as far as step 7, but `mxcubeweb-server -r $(pwd)/mxcubeweb/test/HardwareObjectsMockup.xml/ --static-folder $(pwd)/mxcubeweb/ui/build/ -L debug` doesn't work as `mxcubeweb-server` doesn't appear to exist. There is a mxcube3-server though...

**Comment by mattclarke** [comment]
If I run mxcube3-server with the command instead, I get the following error:
```
> python mxcube3-server  -r $(pwd)/mxcubeweb/test/HardwareObjectsMockup.xml/ --static-folder $(pwd)/mxcubeweb/ui/build/ -L debug
+==================================================================+
| role       | Class  | file                  | Time (ms)| Comment
+==================================================================+
| beamline   | None   | beamline_config.yml   | 0        | File not found
+==================================================================+
Traceback (most recent call last):
  File "/Users/mattclarke/code/others/mxcube/mxcubeweb/mxcube3/__init__.py", line 118, in build_server_and_config
    HWR.init_hardware_repository(cmdline_options.hwr_directory)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/HardwareRepository.py", line 307, in init_hardware_repository
    beamline._hwr_init_done()
AttributeError: 'NoneType' object has no attribute '_hwr_init_done'
Traceback (most recent call last):
  File "/Users/mattclarke/code/others/mxcube/mxcubeweb/mxcube3-server", line 9, in <module>
    main()
  File "/Users/mattclarke/code/others/mxcube/mxcubeweb/mxcube3/__init__.py", line 146, in main
    server, cfg = build_server_and_config()
  File "/Users/mattclarke/code/others/mxcube/mxcubeweb/mxcube3/__init__.py", line 118, in build_server_and_config
    HWR.init_hardware_repository(cmdline_options.hwr_directory)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/HardwareRepository.py", line 307, in init_hardware_repository
    beamline._hwr_init_done()
AttributeError: 'NoneType' object has no attribute '_hwr_init_done'
```
Any ideas?

**Comment by meguiraun** [comment]
can you try with the full path instead of $(pwd) ?

**Comment by mattclarke** [comment]
Okay, that works.
I do get this error, but it doesn't seem to cause any problems as far as I can see:
```
2023-10-04 14:30:33,152 |MX3.HWR|INFO   | MXCuBE 3 initialized, it took 0.6 seconds
Traceback (most recent call last):
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/bin/video-streamer", line 8, in <module>
    sys.exit(run())
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/site-packages/video_streamer/main.py", line 137, in run
    p.start()
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/mattclarke/code/others/mxcube/miniconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'FastAPI.setup.<locals>.openapi'
```

**Comment by meguiraun** [comment]
aah that error! I am not alone anymore! are you using mac?

**Comment by mattclarke** [comment]
Yes!

**Comment by marcus-oscarsson** [comment]
Hm, thats odd. @meguiraun but it works for you on linux then ? 

@mattclarke, @meguiraun, it really should be `mxcubeweb-server` its odd that you get `mxcube3-server` did you get the same on Mac @meguiraun or is that something else then ?

**Comment by fabcor-maxiv** [comment]
> as `mxcubeweb-server` doesn't appear to exist. There is a mxcube3-server though...

I just made a pull request to fix this: https://github.com/mxcube/mxcubeweb/pull/1078

@mattclarke @marcus-oscarsson @meguiraun

**Comment by meguiraun** [comment]
yeah, linux has not been an issue for me. Only seen this in my mac

**Comment by CeciliaCasadei** [comment]
Hello, at step 6 I get the following error:
npm install --legacy-peer-deps
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/ceciliamariacasadei/myData/myDocuments/Cecilia_MAXIV/mxcube_codecamp/mxcubeweb/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/ceciliamariacasadei/myData/myDocuments/Cecilia_MAXIV/mxcube_codecamp/mxcubeweb/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: /Users/ceciliamariacasadei/.npm/_logs/2023-10-06T08_49_53_570Z-debug-0.log

**Comment by fabcor-maxiv** [comment]
Oh...

@CeciliaCasadei, you probably followed the [instructions from the wiki](https://github.com/mxcube/mxcubeweb/wiki#installing-using-conda), right? And if I am not mistaken those were last updated before the [migration to *pnpm* as a replacement for *npm*](https://github.com/mxcube/mxcubeweb/pull/1071). So the wiki is now outdated. Is that correct, @marcus-oscarsson and @axelboc ?

@CeciliaCasadei I think you should use the instructions from the `README.md`, they are probably the most correct ones now.

@marcus-oscarsson @meguiraun I am not sure what is the best way to proceed:

* either update the wiki page to match the latest state (`README.md`);
*  or delete the wiki page and send a new email to everyone with the correct location to find the instructions (`README.md`).

**Comment by CeciliaCasadei** [comment]
I have followed the instructions of the wiki. 
I'll check README.md. Thank you!!

**Comment by meguiraun** [comment]
I changed the wiki to match the readme... for now... as quick fix. Ideally there should only be once place

**Comment by marcus-oscarsson** [comment]
:+1: Thanks @meguiraun. We can remove the wiki after the code camp. I just did not want to do it before to avoid confusion as we already had sent the emails. Then, of course, we forgot to update it :)

**Comment by fabcor-maxiv** [comment]
For correctness:

> npm ERR! enoent ENOENT: no such file or directory, open '/Users/ceciliamariacasadei/myData/myDocuments/Cecilia_MAXIV/mxcube_codecamp/mxcubeweb/package.json'

The issue in there was not strictly about npm vs. pnpm, but the issue was rather that the command was not being run from the correct directory. My mistake. But anyway, this was also the outdated instructions.

**Comment by CeciliaCasadei** [comment]
Hello, step 7 gives an error:

```
mxcubeweb-server -r $(pwd)/mxcubeweb/test/HardwareObjectsMockup.xml/ --static-folder $(pwd)/mxcubeweb/ui/build/ -L debug


Aperture: no position list defined, using default list
Cannot load Hardware Object "/hutchtrigger" : file not found.
WARNING:HWR:Diffractometer: Motor beam_x listed in the centring motor list, but not initalized
WARNING:HWR:Diffractometer: Motor beam_y listed in the centring motor list, but not initalized
WARNING:HWR:Diffractometer: zoom centre not configured
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR.DiffractometerMockup:moving motor {motor} to position {position}
DEBUG:HWR:LdapLogin: connecting to LDAP server ldap.esrf.fr:389
DEBUG:HWR:LdapLogin: got connection <ldap.ldapobject.SimpleLDAPObject object at 0x12c53b670>
ERROR:root:/md_camera: cannot add channel UdiffVersion (hint: check attributes)
ERROR:root:Channel is None
NoneType: None
INFO:HWR:initializing camera object
INFO:HWR:Imported queue entry: XrayCentering2QueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/xray_centering2.py
INFO:HWR:Imported queue entry: XrayCenteringQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/xray_centering.py
INFO:HWR:Imported queue entry: CharacterisationQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/characterisation.py
INFO:HWR:Imported queue entry: EnergyScanQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/energy_scan.py
INFO:HWR:Imported queue entry: GenericWorkflowQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/generic_workflow.py
INFO:HWR:Imported queue entry: OpticalCentringQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/optical_centring.py
INFO:HWR:Imported queue entry: DataCollectionQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/data_collection.py
INFO:HWR:Imported queue entry: SampleCentringQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/sample_centring.py
INFO:HWR:Imported queue entry: AdvancedConnectorQueueEntry from /Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/mxcubecore/queue_entry/advanced_connector.py
DEBUG:HWR:/ednaparams: state changed to 'ON'
ERROR:HWR:Cannot load Hardware Object "/mxlocal" : file not found.
ERROR:HWR:Cannot load Hardware Object "/mxlocal" : file not found.
DEBUG:HWR:diffractcal file not present - using instrumentation.nml /Users/ceciliamariacasadei/myData/myDocuments/Cecilia_MAXIV/mxcube/mxcubeweb/test/HardwareObjectsMockup.xml/gphl/config_esrf_id30b/diffractcal.nml
INFO:HWR:XML-RPC server listening on: :7171
ERROR:HWR:Cannot load Hardware Object "/auto_processing" : file not found.
ERROR:HWR:Cannot load Hardware Object "/parallel_processing" : file not found.
ERROR:HWR:Beamline has no attribute 'run_processing_parallel'
+=======================================================================================================================+
| role                         | Class                        | file                      | Time (ms)| Comment                   
+=======================================================================================================================+
| beamline                     | Beamline                     | beamline_config.yml       | 24       | Start loading contents:   
| session                      | Session                      | session.xml               | 8        |                           
| data_publisher               | DataPublisher                | data_publisher.xml        | 4        |                           
| machine_info                 | MachineInfoMockup            | machine_info.xml          | 5        |                           
| detector                     | DetectorMockup               | detector.xml              | 14       |                           
| beam                         | BeamMockup                   | beam.xml                  | 15       |                           
| transmission                 | TransmissionMockup           | transmission.xml          | 3        |                           
| flux                         | FluxMockup                   | flux.xml                  | 12708    |                           
| cryo                         | ActuatorMockup               | cryo.xml                  | 1        |                           
| energy                       | EnergyMockup                 | energy.xml                | 3        |                           
| resolution                   | ResolutionMockup             | resolution.xml            | 7        |                           
| safety_shutter               | ShutterMockup                | safety_shutter.xml        | 4        |                           
| fast_shutter                 | ShutterMockup                | fast_shutter.xml          | 1        |                           
| hutch_interlock              | None                         | hutchtrigger.xml          | 0        | No object loaded          
| sample_changer               | SampleChangerMockup          | sc.xml                    | 19       |                           
| sample_changer_maintenance   | CatsMaintMockup              | sc_maint.xml              | 3        |                           
| diffractometer               | DiffractometerMockup         | minidiff.xml              | 10597    |                           
| lims                         | ISPyBClientMockup            | lims.xml                  | 2246     |                           
| sample_view                  | SampleView                   | sample_view.xml           | 239      |                           
| queue_manager                | QueueManager                 | queue.xml                 | 15       |                           
| queue_model                  | QueueModel                   | queue_model.xml           | 30       |                           
| beamline_actions             | BeamlineActionsMockup        | beamline_actions.xml      | 10       |                           
| workflow                     | EdnaWorkflow                 | ednaparams.xml            | 12       |                           
| collect                      | MultiCollectMockup           | mxcollect.xml             | 12       |                           
| xrf_spectrum                 | XRFMockup                    | xrf.xml                   | 2        |                           
| energy_scan                  | EnergyScanMockup             | energyscan.xml            | 82       |                           
| gphl_connection              | GphlWorkflowConnection       | gphl/gphl-setup.yml       | 56       |                           
| gphl_workflow                | GphlWorkflow                 | gphl/gphl-workflow.yml    | 80       |                           
| xray_centring                | XrayCentringMockup           | xray_centring2.yml        | 4        |                           
| xml_rpc_server               | XMLRPCServer                 | xml_rpc_server.xml        | 8        |                           
| offline_processing           | None                         | auto_processing.xml       | 0        | No object loaded          
| online_processing            | None                         | parallel_processing.xml   | 0        | No object loaded          
| characterisation             | EDNACharacterisationMockup   | characterisation.xml      | 162      |                           
| beamline                     | Beamline                     | beamline_config.yml       | 26391    | Done loading contents     
+=======================================================================================================================+
+====================================================================================+
| Beamline attribute (id)            | Adapter                 | HO filename              
+====================================================================================+
| data_publisher                     | DataPublisherAdapter    | data_publisher           
| machine_info                       | MachineInfoAdapter      | machine_info             
| detector.detector_distance         | MotorAdapter            | dtox                     
| detector                           | DetectorAdapter         | detector                 
| beam                               | BeamAdapter             | beam                     
| transmission                       | ActuatorAdapter         | transmission             
| flux                               | ActuatorAdapter         | flux                     
| cryo                               | ActuatorAdapter         | cryo                     
| energy.wavelength                  | WavelengthAdapter       | energy                   
| energy                             | EnergyAdapter           | energy                   
| resolution                         | MotorAdapter            | resolution               
| safety_shutter                     | NStateAdapter           | safety_shutter           
| fast_shutter                       | NStateAdapter           | fast_shutter             
| diffractometer.capillary           | NStateAdapter           | capillary                
| diffractometer.beamstop            | NStateAdapter           | beamstop                 
| diffractometer.beamstop_distance   | MotorAdapter            | beamstop_alignment_x     
| diffractometer.frontlightswitch    | NStateAdapter           | udiff_frontlightswitch   
| diffractometer.frontlight          | MotorAdapter            | udiff_frontlight         
| diffractometer.backlightswitch     | NStateAdapter           | udiff_backlightswitch    
| diffractometer.backlight           | MotorAdapter            | udiff_backlight          
| diffractometer.kappa_phi           | MotorAdapter            | udiff_kappaphi           
| diffractometer.kappa               | MotorAdapter            | udiff_kappa              
| diffractometer.sampy               | MotorAdapter            | udiff_sampy              
| diffractometer.sampx               | MotorAdapter            | udiff_sampx              
| diffractometer.phiz                | MotorAdapter            | udiff_phiz               
| diffractometer.phiy                | MotorAdapter            | udiff_phiy               
| diffractometer.phix                | MotorAdapter            | udiff_phix               
| diffractometer.phi                 | MotorAdapter            | udiff_omega              
| diffractometer.zoom                | NStateAdapter           | udiff_zoom               
| diffractometer                     | DiffractometerAdapter   | minidiff                 
+====================================================================================+
2023-10-06 15:59:30,165 |MX3.HWR|INFO   | MXCuBE 3 initialized, it took 26.6 seconds
2023-10-06 15:59:30,287 |HWR    |INFO   | going to poll images
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/mxcubeweb/bin/video-streamer", line 8, in <module>
    sys.exit(run())
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/site-packages/video_streamer/main.py", line 137, in run
    p.start()
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Applications/anaconda3/envs/mxcubeweb/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'FastAPI.setup.<locals>.openapi'
```

**Comment by fabcor-maxiv** [comment]
@CeciliaCasadei 

> AttributeError: Can't pickle local object 'FastAPI.setup..openapi'

As far as I understood it is an error that appears on Mac only... maybe other Mac users will be able to help.

**Comment by meguiraun** [comment]
That error only affects the mockup sample image... The rest of mxcube mockup seems to work despite that.
The line:
2023-10-06 15:59:30,165 |MX3.HWR|INFO   | MXCuBE 3 initialized, it took 26.6 seconds
is what tell us that the hardware objects were loaded

Edit: no, I have no solution for that :(... but @CeciliaCasadei , do you have a mac?

**Comment by marcus-oscarsson** [comment]
@CeciliaCasadei, are you using Mac ? 

For all the Macsters: I tried to make a work-arround for this issue: 

-     You can checkout: https://github.com/mxcube/video-streamer/tree/mac-fix
-     Activate your environment and run pip install

```
git clone https://github.com/mxcube/video-streamer/tree/mac-fix
conda activte mxcubeweb # or other name
pip install
```

And try again, I'm not sure it will work because I don't have  Mac to try with myself

**Comment by meguiraun** [comment]
the error dissapear! thanks! However I still dont see the sample mockup in the canvas

**Comment by fabcor-maxiv** [comment]
Ah... I always disable *video-streamer* (if I understood correctly we do not use it at MAX IV, and I wonder if we could make it an optional dependency, I will create a ticket to discuss this). So maybe if I had not disabled *video-streamer* I would have seen this issue even though I am not on Mac.

**Comment by CeciliaCasadei** [comment]
Yes, exactly, I'm using a Macbook! I'll try the fix, Thank you.

**Comment by AnnieHeroux** [comment]
I am a Mac user (installation today 14 oct 2023 following instruction on README
first the fix for the video_streamer worked,  once i clone the right branch (!)

At this point,  I want to login with idtest0 i get this sql error about user.last_request_timestamp.

2023-10-14 21:17:46,068 |MX3.HWR|ERROR  | 
Traceback (most recent call last):
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.last_request_timestamp

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/AH_ElettraWork/mx3-oct2023/mxcubeweb/mxcube3/routes/login.py", line 48, in login
    res = jsonify(app.usermanager.login(login_id, password))
  File "/Volumes/AH_ElettraWork/mx3-oct2023/mxcubeweb/mxcube3/core/components/user/usermanager.py", line 152, in login
    login_res = self._login(login_id, password)
  File "/Volumes/AH_ElettraWork/mx3-oct2023/mxcubeweb/mxcube3/core/components/user/usermanager.py", line 378, in _login
    active_users = self.active_logged_in_users()
  File "/Volumes/AH_ElettraWork/mx3-oct2023/mxcubeweb/mxcube3/core/components/user/usermanager.py", line 43, in active_logged_in_users
    self.update_active_users()
  File "/Volumes/AH_ElettraWork/mx3-oct2023/mxcubeweb/mxcube3/core/components/user/usermanager.py", line 88, in update_active_users
    for _u in User.query.all():
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/ah/opt/anaconda3/envs/ttt/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.last_request_timestamp
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.username AS user_username, user.nickname AS user_nickname, user.password AS user_password, user.session_id AS user_session_id, user.socketio_session_id AS user_socketio_session_id, user.last_login_at AS user_last_login_at, user.current_login_at AS user_current_login_at, user.last_login_ip AS user_last_login_ip, user.current_login_ip AS user_current_login_ip, user.login_count AS user_login_count, user.active AS user_active, user.fs_uniquifier AS user_fs_uniquifier, user.confirmed_at AS user_confirmed_at, user.requests_control AS user_requests_control, user.in_control AS user_in_control, user.selected_proposal AS user_selected_proposal, user.proposal_list AS user_proposal_list, user.current_limssession AS user_current_limssession, user.limsdata AS user_limsdata, user.last_request_timestamp AS user_last_request_timestamp 
FROM user]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-10-14 21:17:46,074 |MX3.HWR|INFO   | [LOGIN] User idtest0 could not login ((sqlite3.OperationalError) no such column: user.last_request_timestamp
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.username AS user_username, user.nickname AS user_nickname, user.password AS user_password, user.session_id AS user_session_id, user.socketio_session_id AS user_socketio_session_id, user.last_login_at AS user_last_login_at, user.current_login_at AS user_current_login_at, user.last_login_ip AS user_last_login_ip, user.current_login_ip AS user_current_login_ip, user.login_count AS user_login_count, user.active AS user_active, user.fs_uniquifier AS user_fs_uniquifier, user.confirmed_at AS user_confirmed_at, user.requests_control AS user_requests_control, user.in_control AS user_in_control, user.selected_proposal AS user_selected_proposal, user.proposal_list AS user_proposal_list, user.current_limssession AS user_current_limssession, user.limsdata AS user_limsdata, user.last_request_timestamp AS user_last_request_timestamp 
FROM user]
(Background on this error at: https://sqlalche.me/e/20/e3q8))

**Comment by fabcor-maxiv** [comment]
Code camp has come and gone.
