### ISSUE TITLE
Investigate running the back end without Redis non-production purposes

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1065]
Currently the Sphinx documentation (in `docs`) relies on the usage of [`autoflask` directive](https://sphinxcontrib-httpdomain.readthedocs.io/en/1.8.0/#directive-autoflask) in order to build the REST API documentation based on the Flask routes. This requires actually running the back end end server, which requires running a Redis server.

Maybe for this specific purpose -- building the documentation -- and other similar, non-production purposes such as unit testing, it would be possible to run the back end server without having a Redis server. This would simplify those processes greatly and surely improve the performance of CI/CD (less time needed to finish the pipelines/workflows).

**Comment by fabcor-maxiv** [comment]
> Currently the Sphinx documentation (in `docs`) relies on the usage of [`autoflask` directive](https://sphinxcontrib-httpdomain.readthedocs.io/en/1.8.0/#directive-autoflask)

As far as I can tell, his is also true for `autodoc` and `autosummary`.

**Comment by fabcor-maxiv** [comment]
See also: https://github.com/mxcube/mxcubeweb/issues/1262#issuecomment-2191145674

**Comment by axelboc** [comment]
Redis is tricky to install/run on Windows, and this currently prevents me from working on MXCuBE when I work from home.

**Comment by fabcor-maxiv** [comment]
> Redis is tricky to install/run on Windows

Even with conda, Docker or WSL?

Anyway, yes, I feel like we could make it possible to at least start MXCuBE without Redis. It seems like it would simplify a bunch of things (generating documentation is only one of them).

My impression is that we check early on if Redis is running and fail if it isn't. Maybe I am completely wrong, because I have not actually investigated this, but it feels like it fails even though in many cases Redis is not used at all and maybe we could get rid of of this check without breaking anything. It seems like there are many other dependencies that might not be available and MXCuBE still starts fine, not sure why Redis seems to be a special case here.

**Comment by axelboc** [comment]
> Even with conda, Docker or WSL?

I tried only with conda but I should try with Docker and WSL, you're right.

**Comment by marcus-oscarsson** [comment]
We used to persist the queue, session and certain settings for recovery to `redis` but we are no longer using this. So we can actually remove the `redis` dependency on `mxcube-web` it will however still be needed in `mxcubecore`.  The dependency on `mxubecore` wont prevent the application from running but the `DataPublisher`, for instance` wont work so its perhaps to be avoided for tests. It should work fine for docs and demo/mockups.
