### ISSUE TITLE
Can *mxcube-video-streamer* be listed as optional dependency?

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1082]
If I understood correctly we do not use *mxcube-video-streamer* at MAX IV, and I wonder if we could make it an optional dependency of *mxcubeweb*. Maybe there are other dependencies or groups of dependencies that are not in use at some facilities and that could be made optional.

**Comment by marcus-oscarsson** [comment]
As we discussed per video, it would be nice if you could try the `mxcube-video-streamer` to see if it suits your needs. If it does we can remove the "built-in" MJPEG streamer.

I'm closing this issue in the mean time
