### ISSUE TITLE
 Generate Sphinx documentation from Python code and docstrings

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1099]
Let Sphinx generate documentation pages based on the Python code and its docstrings.

**Comment by marcus-oscarsson** [comment]
And there shall be light ;)

**Comment by fabcor-maxiv** [comment]
We can think about something similar for the Javascript in the UI part of the code: https://github.com/mxcube/mxcubeweb/issues/1100
