### ISSUE TITLE
Python 2.6 compatibility

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#11]
At the moment MXCuBE 3 is not compatible with Python 2.6, at least because of the dependency
on the `socketio` library, indeed it is using dict comprehensions which only exist for Python >= 2.7:

```python
Traceback (most recent call last):
  File "/usr/local/bin/mxcube3", line 5, in <module>
    from mxcube3 import app, socketio
  File "/usr/local/lib/python2.6/dist-packages/mxcube3/__init__.py", line 2, in <module>
    from flask.ext.socketio import SocketIO
  File "/usr/local/lib/python2.6/dist-packages/flask/exthook.py", line 62, in load_module
    __import__(realname)
  File "/usr/local/lib/python2.6/dist-packages/flask_socketio/__init__.py", line 3, in <module>
    import socketio
  File "/usr/local/lib/python2.6/dist-packages/socketio/__init__.py", line 2, in <module>
    from .server import Server
  File "/usr/local/lib/python2.6/dist-packages/socketio/server.py", line 7, in <module>
    from . import packet
  File "/usr/local/lib/python2.6/dist-packages/socketio/packet.py", line 115
    for key, value in six.iteritems(data)}
      ^
SyntaxError: invalid syntax
```

Not sure if it is important, though.

At ESRF at the moment our default installation comes with Python 2.6 but we can change that I guess.

**Comment by meguiraun** [comment]
2.6 is also our default version at MaxIV, in fact, I run all of this code under 2.6 without that problem. I think I might have an older version installed. So these are my versions:

Flask (0.10.1)
Flask-SocketIO (0.3.8)
Flask-WTF (0.9.5)
gevent (1.0.1)
gevent-socketio (0.3.6)
gevent-websocket (0.9.3)

Moving to python 2.7 is also a discussion point in our site, I think we can move forward for the mxcube development related stuff.

Could you post your version numbers?

**Comment by mguijarr** [comment]
Flask==0.10.1
Flask-SocketIO==0.6.0 **different version**
gevent==1.0.1
gevent-socketio==0.3.6
gevent-websocket==0.9.5  **different version**

I guess we should just update `requirements.txt` with the right version numbers for the moment,
to have something running. Then we can decide what to do with 2.7...

What do you think ?

**Comment by meguiraun** [comment]
I agree with you, now looks as the best solution. 

We can discuss in detail later, but since we are using modern tools (e.g. react, web, etc...) it does not make sense to stay with python 2.6 forever...

**Comment by mguijarr** [comment]
I close this issue for now, will re-open after we talk about Python 2.7 - for me we can proceed with
upgrade, but let's not disturb ourselves with such details now
