### ISSUE TITLE
two issues about running queue

### ISSUE THREAD

**Issue by JieNanMAXIV** [mxcube/mxcube3#110]
1. When running a single task, one will get the error msg "'RootNode' object has no attribute 'lims_id'" 
The problem is when the server calls to execute the child entry directly, the lims_id is not provided, which otherwise would be assigned with the sample.lims_id when running a queue.

2. When running a queue, one will get error msg "Sample' object has no attribute 'lims_group_id' ", 
This is because the Taskgroup node, which contains lims_group_id, is missing in the queue created by the server.  

To temporarily avoid this error, one solution is to add the following line in the queue_model_objects_v1.py, line 214, where Sample obj is initialized
self.lims_group_id = None,

**Comment by meguiraun** [comment]
As it is now, the *parent* of any method (e.g. DataCollection) is a sampleNode in the queue, so it does not have any ```lims_group_id```.

Moving to a taskGroup based queue in the next milestone?

**Comment by marcus-oscarsson** [comment]
@JieNanMAXIV Please close this if its resolved 

Thanks,
Marcus

**Comment by mguijarr** [comment]
@JieNanMAXIV Can we close this ?
