### ISSUE TITLE
Generate documentation from Javascript code in the UI part

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1100]
In the spirit of https://github.com/mxcube/mxcubeweb/issues/1099 maybe it is possible to achieve something similar from the Javascript code in the UI part of MXCuBE-Web.

**Comment by fabcor-maxiv** [comment]
Maybe @axelboc has suggestions.

**Comment by axelboc** [comment]
Just to clarify, what do we need to document in the front-end? I get documenting the REST API, but I've never been a huge fan of documenting a codebase as a whole — it's difficult to keep up to date, makes writing new code tedious, duplicates the code itself when it's already perfectly understandable, and tends to block developers from making broad refactoring. I'm more of a "code should be understandable by itself" and "add comments only where it makes sense" kind-of-person. :grin:

That being said, to answer your question, plenty of tools can generate documentation from [JSDoc](https://jsdoc.app/) comments.

**Comment by fabcor-maxiv** [comment]
@axelboc

In principle the idea is to have something like what I am working on for Python, which was asked for by Rasmus at the code camp:

* https://mxcubecore--806.org.readthedocs.build/en/806/dev/autosummary/mxcubecore.BaseHardwareObjects.html#mxcubecore.BaseHardwareObjects.HardwareObjectNode.get_objects

This is all automatically generated, with every merge (there is even a preview with each pull request like the link above). So there is no work to be done, except maintaining the infrastructure if it breaks (GitHub workflows, update tool dependencies, and so on).

For many devs, I guess there is no need for such a thing as it is already in the IDE. But for some who do not use such IDE (like me), it can be helpful (although I often just browse the code itself).

This is not a priority, but a nice to have. And if the cost gets too high, we should not think too long before getting rid of it because then it becomes more of a hindrance than a help.

We can investigate if it is possible to have something like the output of JSDoc be integrated in the Sphinx doc.

**Comment by axelboc** [comment]
Yeah, I mean for `mxcubecore` it makes total sense, since it also exposes an API. I just don't get what the API to document is, in the front-end — there's no shared components library, and even internally it's not clear which components are designed for re-use. Perhaps the Redux actions? But then they kind of map to back-end API calls already, so having another documentation for them might be redundant. :shrug: 

I would be more inclined to write a tailored documentation with recipes for doing various things (connecting to the Redux store, dispatching an action, writing a new action+reducer, etc.)

**Comment by fabcor-maxiv** [comment]
I understand. I would say we keep this ticket open for a week or so and unless we come up with some actual helpful use case for this then we can close the ticket.

**Comment by fabcor-maxiv** [comment]
I close this now after one week. Of course we can reopen anytime if/when someone feels like it is worth it.
