### ISSUE TITLE
The pnpm lock file seems to be out of sync with `package.json`

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1115]
It seems like the *pnpm*  *lockfile* is out of sync with the content of `package.json`.

I am about to submit a pull request to update the lockfile. But I am also wondering if we can make sure we do not get out of sync again. Ideally we would have a solution that can be embedded in a pre-commit hook. Anyone knows of such a hook? Otherwise the next best thing is to check explicitly in a GitHub Action.

@axelboc

**Comment by axelboc** [comment]
The CI is supposed to fail when running `pnpm install` with an out-of-date lock file. That's because when `CI=true`, pnpm runs `pnpm install` with the `--frozen-lockfile` flag.

If the CI doesn't fail, then there's a problem somewhere... Perhaps the `CI` env var is not set for some weird reason...

**Comment by axelboc** [comment]
Generally speaking, I'm not a huge fan of pre-commit hooks as they can slow down committing a lot, even for simple things. I prefer well-configured IDEs and well-documented development practices (like linting/testing before pushing). Of course it can be frustrating to wait for the CI to run ... only to see it fail, so I'm not entirely opposed to pre-commit hooks. It's just that in this case, changing `package.json` is not something we do often, so I would recommend letting the CI do its job.

**Comment by fabcor-maxiv** [comment]
@axelboc 

Agreed, if running pre-commit hooks takes too much time, then they are counter-productive and should be removed. I do not know if such a hook would be time consuming or not, I could not find one anyway, so that's done.

So I guess now I will try to check if the CI pipeline needs fixing or if something was merged while pipeline was red.

**Comment by fabcor-maxiv** [comment]
I guess I got confused between remotes and branches somewhere. The lock file here on `develop` seems to be up-to-date after all. I close this ticket for now.
