### ISSUE TITLE
Sphinx material theme

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1116]
There is quite nice theme for the documentation called material that is used alot with `mkdocs`. I find it very easy on the eyes :)  Examples: https://bashtage.github.io/sphinx-material/ , https://fastapi.tiangolo.com/

It would be nice to give it a try :)

**Comment by fabcor-maxiv** [comment]
* PR on mxcubecore:
  * https://github.com/mxcube/mxcubecore/pull/867
  * Preview:
    * https://mxcubecore--867.org.readthedocs.build/en/867/

**Comment by marcus-oscarsson** [comment]
Closing this one
