### ISSUE TITLE
Cypress as optional dependency?

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1117]
At MAX IV we have some particular circumstances that make it inconvenient to have *cypress* as a dependency of the web UI (in `ui/package.json`). The short version of it is that in some cases we want to run `pnpm install` and `pnpm run build` in a restricted network, but *cypress* requires web access.

I noticed there is a thing called [`optionalDependencies`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies) that seems like it could help us in our use case, but I am not entirely sure this would behave as we expect and most importantly without penalizing anyone else. If *cypress* were to be moved to `optionalDependencies` it seems like we could run [`pnpm install --no-optional`](https://pnpm.io/cli/install#--no-optional) in our restricted network, but what would be the consequences for others? Any unwanted side effect we should consider?

Any thoughts?

@axelboc

**Comment by axelboc** [comment]
If `pnpm install` works in your restricted network, then I'm sure your IT team can make the Cypress installation work as well somehow. It'd be a shame for your not to be able to run Cypress locally. There is a note about configuring proxies on Cypress' [Getting Started guide](https://docs.cypress.io/guides/getting-started/installing-cypress). Perhaps it will help?

**Comment by axelboc** [comment]
Lots more info on this page: https://docs.cypress.io/guides/references/advanced-installation

**Comment by fabcor-maxiv** [comment]
We have another workaround for now.

**Comment by marcus-oscarsson** [comment]
Just a short comment on this as we also discussed it on our meeting. My understanding is that the reason you need to remove this dependency is that the machine from where you deploy is not allowed to perform certain requests. This machine is also used to build the frontend. A solution as we mentioned during the meeting would be to build and test the bundle on a different machine and then deploy it on the machine in question.

I think we should,as far as possible, try to avoid optional dependencies. For the simple reason that we simply want to as a large extent as possible the same software running everywhere. Then ofocurse we have to try to take the reality and infrastructure of each site into account, so I understand that you might need to special tricks to get around certain "limitations".

**Update:** So what was finally the solution you found ?

**Comment by fabcor-maxiv** [comment]
This is quite closely related to https://github.com/mxcube/mxcubeweb/issues/1114. Cypress is a test/dev dependency so the logical step is to reach for `pnpm install --prod`, but then `pnpm build` does not work.

Anyway, this seems to be a settled matter for now on our side. Our current solution is not ideal but good enough, we might want to revisit this at a later point.


> A solution as we mentioned during the meeting would be to build and test the bundle on a different machine and then deploy it on the machine in question.

Of course, this would be the right way. But not possible for us right now, we might do something like this in the future.


> So what was finally the solution you found ?

In that environment, we remove *cypress* from `package,json` before installing. As I said, far from ideal but it gets us moving forward. Some blame lies on our current setup which is a bit unusual and hard to work with.


> I think we should,as far as possible, try to avoid optional dependencies. For the simple reason that we simply want to as a large extent as possible the same software running everywhere.

Cypress is not a runtime dependency.


> If `pnpm install` works in your restricted network, then I'm sure your IT team can make the Cypress installation work as well somehow. It'd be a shame for your not to be able to run Cypress locally. There is a note about configuring proxies on Cypress' [Getting Started guide](https://docs.cypress.io/guides/getting-started/installing-cypress). Perhaps it will help?

We have no need to run the end-to-end test suite in that particular environment. We run it in a different environment.


Thanks  :)
