### ISSUE TITLE
[Queue] Enhanced design

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#112]
The needs to be redesigned:
* Methods should be attached to centring positions
    - So… redesign both the server and the client, additional queue level needed
    - A design review of the queue (VIEW) is needed, what we have been working on does not seem to fulfil the requirements of the experiment
* In the server side methods should hang from TaskGroupNode? (currently from SampleNode)

**Comment by marcus-oscarsson** [comment]
I'm closing this one since it seems to be resolved, at least by looking at the latest source. 
@meguiraun Plase let me know (re open) it if its not the case
