### ISSUE TITLE
HTTP Error codes

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1126]
- Review the http error codes to make sure that they confirm to commonly used standards
- Remove redirect from `signout` route

**Comment by axelboc** [comment]
There is also a redirect to `/login` in the `/login_info` route: https://github.com/mxcube/mxcubeweb/blob/develop/mxcubeweb/routes/login.py#L98. It should respond with a [401 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) instead, I think, though this will likely have an impact on the front-end.

**Comment by marcus-oscarsson** [comment]
Done
