### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#114]
By means of the flask-session (or an additional llibrary e.g. flask-login) keep track of the user currently logged in (the authentication is done through the IspybClient)
* Store the current user
* Provide a way of blocking some api calls if not logged in (to be decided later which calls should be blocked, all of them?); sth like [mxlogin_required] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/Utils.py) 
* Remember the user
* Related to #58

**Comment by mguijarr** [comment]
Can we close this issue or not yet?

**Comment by meguiraun** [comment]
I would say yes
