### ISSUE TITLE
Move content from Wiki to `/docs`

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1153]
Same as for [`mxcubecore`](https://github.com/mxcube/mxcubecore/issues/831)...

Now that we have the setup with Sphinx (and ReadTheDocs) automatically building documentation, and now that we have the "documentation camp" in perspective, I want to start working a bit more on content. First things first, I want to move the content of the Wiki into the new Sphinx-based setup in `/docs`.

So, this is a follow-up of https://github.com/mxcube/mxcubeweb/issues/1053.

**Comment by fabcor-maxiv** [comment]
I am not quite sure what in the Wiki is still relevant and is worth migrating to `/docs`. Anyone has an overview?

**Comment by marcus-oscarsson** [comment]
@fabcor-maxiv thanks its a good initiative !

My understanding is that [Tutorial](https://github.com/mxcube/mxcubeweb/wiki/Tutorial) was added recently and that the section about [sample changer](https://github.com/mxcube/mxcubeweb/wiki/Sample-Changer-changes-and-Sample-Changer-maintenance) is still fairly up to date. The rest can be removed in my opinion, or perhaps rewritten in a better way.

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson I added the tutorial and the page about the sample changer to `/docs` (and some other changes) in the PR https://github.com/mxcube/mxcubeweb/pull/1154

**Comment by fabcor-maxiv** [comment]
Deprecation notices added to the Wiki:

* https://github.com/mxcube/mxcubeweb/wiki/Home
* https://github.com/mxcube/mxcubeweb/wiki/Frontend-development-stack
* https://github.com/mxcube/mxcubeweb/wiki/Installing-MXCuBE-WEB-versions-prior-to-4.x
* https://github.com/mxcube/mxcubeweb/wiki/Running-MXCuBE3
* https://github.com/mxcube/mxcubeweb/wiki/Sample-Changer-changes-and-Sample-Changer-maintenance
* https://github.com/mxcube/mxcubeweb/wiki/Tutorial
* https://github.com/mxcube/mxcubeweb/wiki/User-interface-and-server-data-interchange
* https://github.com/mxcube/mxcubeweb/wiki/User-interface-and-server-message-handler
