### ISSUE TITLE
Dependencies `mxcubecore` and `mxcube_video_streamer` are pinned

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1159]
I wonder why the dependencies `mxcubecore` and `mxcube_video_streamer` are pinned to a specific version in `pyproject.toml`: https://github.com/mxcube/mxcubeweb/blob/c5f23ec964b3feb4b7c7a349a927cc49003bd213/pyproject.toml#L42-L43

Would it be possible to use a loose version constraint for those? Especially since we have the lockfile anyway.

**Comment by marcus-oscarsson** [comment]
Yes, it would actually be better to loosen them

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson I will work on this.

1. What version constraint do we want?

    *  I believe `>=` is the most reasonable operator, because I doubt we are scrupulously following semantic versioning (virtually no one does, and strict upper bounds are only causing problems).
    * Do we know what would be the lowest bound for mxcubecore? `1.0`? Or should I just user the current value `1.54.0`?

    So maybe:

    ```toml
    mxcubecore = ">= 1.54.0" 
    mxcube-video-streamer = ">= 1.0.0" 
    ```

2. I intend to update the locked versions as well. Notably because I would like to have `ispyb-client` disappear from the lockfile. I can try to get the latest versions of mcubecore and mxcube-video-streamer in the lockfile. Hopefully I manage without having all the other dependencies change versions.

**Comment by marcus-oscarsson** [comment]
Thanks alot @fabcor-maxiv very nice initiative, I was about to do this as well but have had more pressing things to look at so I appreciate that you have a look :) 

Yes I think that `>=` is fine especially as we are in complete control of both mxcubecore and mxcube-video-streamer.

:+1:
