### ISSUE TITLE
Datacollection default params

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#116]
add default params to the data collection popup

**Comment by mguijarr** [comment]
Default parameters are stored in beamline setup xml file, have to be sent from server to client

**Comment by mguijarr** [comment]
@meguiraun I guess we can close this as #275 and #277 have been merged?

**Comment by marcus-oscarsson** [comment]
I'm closing this one since its resolved, there are still hard coded values on the server but the basic functionality is there.
