### ISSUE TITLE
LDAP dependencies in GitHub Actions workflows

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1165]
In some GitHub Actions workflows we explicitly install LDAP dependencies outside of the conda environment directly on the system. We can probably get rid of this step because the LDAP dependencies are installed in the conda environment.

**Comment by fabcor-maxiv** [comment]
I became aware of this when investigating why some jobs recently failed:

* https://github.com/mxcube/mxcubeweb/actions/runs/7756389610/job/21153590022
* https://github.com/mxcube/mxcubeweb/actions/runs/7756389603/job/21153590281
* https://github.com/mxcube/mxcubeweb/actions/runs/7756389603/job/21153590652
* https://github.com/mxcube/mxcubeweb/actions/runs/7756389603/job/21153590005

They all failed trying to install LDAP as system dependencies (for an unknown reason).

As far as I can tell installing LDAP as system dependencies is not necessary since we install LDAP in the conda environments.

**Comment by fabcor-maxiv** [comment]
Some general clean-up might be needed as well:

* always use conda environment for better consistency
* do not install Python project if we only want to format and lint the JavaScript code

**Comment by marcus-oscarsson** [comment]
I did not even notice that the job failed, shame on me. I simply looked at the change which was trivial enough :). Thanks for fixing the CI nice initiative !
