### ISSUE TITLE
Question on : component not accessible via Beamline

### ISSUE THREAD

**Issue by HilbertCorsair** [mxcube/mxcube3#1244]
My MXCuBE web app fails after login due to a problem with the diffractometer HO. The error comes from the front end in the file mxcubeweb/ui/src/containers/SampleViewContainer.js line 135 [here](https://github.com/mxcube/mxcubeweb/blob/develop/ui/src/containers/SampleViewContainer.js) because the `diffactometerHo` constant is none and does not have a `state` property.
In the mxcubeweb/App.py file there is a static method : `get_ui_properties()` that contains a try - except block [file here](https://github.com/mxcube/mxcubeweb/blob/develop/mxcubeweb/app.py) 
This is where the app fails because the `adapter` variable is `None`. The message printed in the console comes from the except block and says "... not accesible via Beamline". Does this mean that I need to define my component in the mxcubecore/HardwareObjects/Beamline.py (with the `@property` decorator) ? So if for example my component.attribute is diffractometer.phy do I need to modify the definition of the diffractometer property in the Beamline.py file?

**Comment by beteva** [comment]
@HilbertCorsair, please check if you have the right diffractometer configuration - it looks to me like there might be a typo and you actually need diffractometer.phiy and not diffractometer.phy. Otherwise the answer is no - you do not need to modify the definition of the diffractometer property in the Beamline.py file.

**Comment by HilbertCorsair** [comment]
Thank you @beteva ! I checked the configuration together with Pierre and everything seems ok on the back end. I wasn't able to find the problem but as of this post I was able to track the error to the front side in the mxcubeweb/core/components/beamline.py at line 147 : `data = ho.dict()`. [file here](https://github.com/mxcube/mxcubeweb/blob/develop/mxcubeweb/core/components/beamline.py)  The dict() method fails. Exploration continues .

**Comment by HilbertCorsair** [comment]
Thank you @beteva, Yesterday I looked over the configuration with Pierre but everething seems ok on the backend. I'm still working on finding the problem that causes the UI to crush.

**Comment by HilbertCorsair** [comment]
Still no success with the diffractometer HO. After entering the login the application UI fails with "Unexpected Applicatoion Error! " The diffractometerHo variable is stil undefiend in the mxcubeweb/ui/src/containers/SampleViewContainer.js line 135.  The MXCuBE server console prints a warning: diffractometer.phi not accesible via Beamline object. This gets printed for all diffractometer motors. The xml configuration files seem ok and there are also prints confirminf the defractometer motors position is updated. Would anyone be available for a quick zoom video session @beteva @marcus-oscarsson @fabcor-maxiv ?  I could explain better the problem if i can share some code.

**Comment by HilbertCorsair** [comment]
When Running MXCuBE in developer mode I also get an watchpack error: Watchpack error (initial scan): ENODEV: no such device, lstat "/path/.  @marcus-oscarsson  any suggestions? I suspect this has to do with the develpment environmet and not so much with the MXCUBE app itself but I could be worng .

**Comment by fabcor-maxiv** [comment]
@HilbertCorsair

It is not something I am familiar with, I do not think I can help here. : /

If it is related to the Javascript web frontend UI, then maybe @axelboc has some suggestions.

**Comment by HilbertCorsair** [comment]
I also noticed that there is a problem in: mxcubeweb/core/adapter/beamline_adapter.py in : 
`_d = self.app.mxcubecore.get_adapter(attr_name).dict()` 
there is an exceprion when `attr_name` is `beam.zoom`

This fails (at least for _id = "beam.zoom" ). 
The beam.zoom object in my case doesn't corespond to the pydantic model. 
When the dict() method is applyed to this adapter it results in a Pydantic Validation Error.
I guess I need to write a new pydantic model for our specific zoom HO. 
This is an issue that will most likely afect the other diffractomemer motors too so I will make the permanent switch to the xml_yaml_conversion banch and will look to develop with the yaml configuration going forward.
