### ISSUE TITLE
Saving prameter values in forms

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcube3#1256]
This has been added in PR #1253.
Can anyone tell me if this is also active in the JSON-Schema-driven popups made by Jean-Baptiste for Global Phasing?

The point is that for popups that are generated by code, complete with setting of default values, one does *not* want to reuse the last parameter values. If the GPhL workflow pops up a UI for a new crystal or a new acquisition step, you want it to use the default values set by the code, not the values used last time for a different crystal, which may be completely inappropriate.

**Comment by marcus-oscarsson** [comment]
Hi @rhfogh, 

Keeping / (carrying over) the parameters from previous dialogs is not possible in the GPhL workflow dialogs. Ill close the issue, please feel free to re-open if I did not answer your question

**Comment by rhfogh** [comment]
Excellent. Please do close the issue.
