### ISSUE TITLE
UI: missing gap between top-right corner widgets

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1261]
When running MXCuBE with mock-up beamline configs, the gap between 'Detector' and 'Fast Shutter' widgets is missing:

![image](https://github.com/mxcube/mxcubeweb/assets/77584583/c8d9dca8-011e-4b17-83bb-f9e867603b2d)

We should have consistent gaps for these widgets.

**Comment by marcus-oscarsson** [comment]
Noticed, I've fix for it :)
