### ISSUE TITLE
Export Python dependencies as *pip* `requirements.txt`

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1268]
It seems like for some facilities (including us at MAXIV to some extent), it is more practical to install MXCuBE-Web with pip (instead of Poetry).

As explained in [Deployment](https://mxcubeweb.readthedocs.io/en/latest/dev/deployment.html) ([permalink](https://github.com/mxcube/mxcubeweb/blob/a79b64e1cc6fe6f852897c5ae1c91efef1774c13/docs/source/dev/deployment.md)), the issue is that by installing with pip we lose the advantage of Poetry's lockfile (pip can not read Poetry's lockfile so it ignores it). This results in unpinned dependencies being installed during deployment to production, and potential issues...

We can take advantage of Poetry's `export` command and the *pre-commit* hooks to automatically generate a `requirements.txt` file that contains the pinned dependencies and that pip can read. This could help provide repeatable installations in production environments.

**Comment by marcus-oscarsson** [comment]
Great idea !
