### ISSUE TITLE
System log is not saved after refresh or with a new tab/window

### ISSUE THREAD

**Issue by JieNanMAXIV** [mxcube/mxcube3#127]
After normal logout (pressing the logout button), the logging history remains after relogin. 
However, if one does refresh or opens a new tab/window, one needs to login again. Also the logging history is gone.

**Comment by mguijarr** [comment]
Is this solved by latest PR from Fredrik, with the *reduxification* of logging ?

**Comment by bolmsten** [comment]
In theory yes but as we do not at the moment restore the session state it will not work

**Comment by mguijarr** [comment]
Several options:
- accept that it's cleared on refresh
- recover it from local storage (redux persist, client side storage)
- recover it from server
