### ISSUE TITLE
Replace Create React App with Vite

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1273]
[Create React App](https://create-react-app.dev/docs/getting-started), through its `react-scripts` package, has not received updates since [April 2022](https://github.com/facebook/create-react-app/releases). It is time to move to another build tool and I've had good experiences so far with [Vite](https://vitejs.dev/) ... and so has the [web community](https://2023.stateofjs.com/en-US/libraries/build_tools/#build_tools_ratios).

**Comment by fabcor-maxiv** [comment]
Godspeed!
