### ISSUE TITLE
Checkbox labels should be clickable in RA Options

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1279]
![image](https://github.com/mxcube/mxcubeweb/assets/2936402/532dc627-1e39-449b-a9d1-11738391cd98)

Also, random question: what does "Enable remote access" actually do? Because I can still give/take control even when it's unchecked. Am I missing something? (I run the mock beamline.)

**Comment by marcus-oscarsson** [comment]
Yes but you cannot or should not be able to login as observer if its disabled

**Comment by axelboc** [comment]
Hmm, I seem to be able to.

**Comment by marcus-oscarsson** [comment]
I think its because you are logged-in from localhost to be verified but there is special handling of localhost

**Comment by axelboc** [comment]
Right, okay, maybe the checkbox should be disabled in that case, then?
