### ISSUE TITLE
Logging out remote users doesn't log them out from the UI

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1282]
They're only logged out if they refresh the page:

![Peek 2024-07-02 16-52](https://github.com/mxcube/mxcubeweb/assets/2936402/ee8ccee7-1ecd-4824-83dd-66ecdc4b4a77)

**Comment by marcus-oscarsson** [comment]
They are logged out in the sense that they cant do anything or receive any update, but it would indeed be better if they are also "forwarded" to the logout page
