### ISSUE TITLE
Context menu on samples list stays open

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1304]
This is really unexpected and quite annoying especially since it stays open even after navigating away and back to the samples list page.

![Peek 2024-07-11 09-40](https://github.com/mxcube/mxcubeweb/assets/2936402/6c963cf1-c6e9-4732-8586-96805d1f3c13)

**Comment by marcus-oscarsson** [comment]
Yes, and its a bit awkward that it is animated from the bottom up in my opinion.

**Comment by marcus-oscarsson** [comment]
@jbflo Is it something you think you can have look at when you get some time ?

**Comment by walesch-yan** [comment]
The context menu on the canvas element in the data collection section shows the exact same behavior. From my understanding, the only way to close them is by clicking on the element that spawned them (i.e. sample, resp. canvas) or its direct parent element. Clicking anywhere on the screen to close them would be a more intuitive solution.

**Comment by jbflo** [comment]
Maybe we should check again with react-contexify or reat contexMenu that have the necessary  events handlers to show or Hide on body click, but in the pass they had some bugs when dealing with long Menu Height. So we had to create this Context Menu component where Show or Hide state are from redux,  But forgot to handle the hide when component is Unmounted.  Please have a look at the
Related [PR](https://github.com/mxcube/mxcubeweb/pull/1321) for a fix

**Comment by axelboc** [comment]
Concerning UX, the context menu should ideally be closed right after selecting a menu item. This is what you expect from a typical OS context menu. Unmount is a good start though, I'm not against merging that to mitigate the issue when navigating away and back.

Concerning implementation, if the underlying library can't handle the above easily out of the box, then the state should ideally be managed locally for efficiency and to avoid cluttering global state. But this could be refactored later on, of course.

**Comment by axelboc** [comment]
Resolved in #1321
