### ISSUE TITLE
Icon to copy path is incorrect

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1308]
This is a _paste_ icon:

![image](https://github.com/mxcube/mxcubeweb/assets/2936402/487aa9a6-4681-4ad3-9ffa-0f4112e37aa2)

**Comment by fabcor-maxiv** [comment]
There should be text ~"paste"~ "copy" first, and then maybe an icon second. Just an icon is often unclear.

**Comment by marcus-oscarsson** [comment]
Well, the copy hum hum "paste" icon is quite standard so most people would know what is meant but its true that the correct icon and a "copy" label would be nice :)

**Comment by axelboc** [comment]
Here it is with the right icon:

![image](https://github.com/mxcube/mxcubeweb/assets/2936402/32832288-00d8-4369-ba2f-ec3200d920d1)

I feel like it's clearer now, and there's a "Copy path" tooltip, so maybe adding the text is not required.

**Comment by fabcor-maxiv** [comment]
I almost always prefer with text label, but let's not prevent this from making other improvements, this is already clearer with the icon change : )
