### ISSUE TITLE
"Prefix" field in error state when opening collection/characterisation modals for some samples

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1310]
With mock sample `A-TIM - fghfg` there's no issue, but with `B2 hexa - sample`, the field is in error state. It appears that some spaces aren't properly escaped:

![image](https://github.com/mxcube/mxcubeweb/assets/2936402/6a9aefe7-40f9-457e-9129-609d316dafc0)

**Comment by marcus-oscarsson** [comment]
I think it might be the space " " I'm not sure though why it works for the first sample, there should be a similar warning on the back end as well (when synchronizing with LIMS)

**Comment by axelboc** [comment]
No longer relevant since the mock samples no longer contain spaces in their names.
