### ISSUE TITLE
Step input popover is a bit cumbersome to use

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1311]
The step input popover has a few flaws:

- It requires too many user interactions to change the step.
- The up/down arrow buttons to adjust the step are apparently rarely used because it's often quicker to enter a value manually (especially since some of the increments are not well configured by default - e.g. 0.1 for Omega is way too small).
- The checkmark button feels unnecessary since one is already typing a value, so pressing <kbd>Enter</kbd> is faster.
- When the step changes, the motor input becomes "dirty" for no apparent reason (i.e. orange background, indicating that the value of the input has changed but hasn't yet been sent to the server).

![Peek 2024-07-11 11-14](https://github.com/mxcube/mxcubeweb/assets/2936402/13a25c7f-f93e-41f3-bdf7-2690d41dca57)

**Proposal:** Turn the step value into an input field that can be edited directly and committed with <kbd>Enter</kbd> (no up/down arrow buttons). The step input should be marked as dirty when edited but not yet committed (but not the motor input).

This solution would also greatly simplify the logic of the step component, since it currently deals with disabling the popover behaviour when the motor input is already displayed inside a popover:

![image](https://github.com/mxcube/mxcubeweb/assets/2936402/74a64ab8-7aa5-4f84-833b-59d5fa852f4a)

**Comment by marcus-oscarsson** [comment]
Yes, the step function is indeed not used very often. Your suggestions sounds good to me as well, lets go for that if there are no other objections :)
