### ISSUE TITLE
Issues with end-to-end test with Cypress

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1341]
The end-to-end tests with Cypress tend to never succeed. As pointed out in <https://github.com/mxcube/mxcubeweb/pull/1340#issuecomment-2288530921> they fail with: "_Cypress failed to make a connection to Firefox_", for example in the following jobs:

* https://github.com/mxcube/mxcubeweb/actions/runs/10386697377/job/28760411249
* https://github.com/mxcube/mxcubeweb/actions/runs/10386591757/job/28758199143
* https://github.com/mxcube/mxcubeweb/actions/runs/10385971960/job/28756235987
* https://github.com/mxcube/mxcubeweb/actions/runs/10383934472/job/28749858812

**Comment by walesch-yan** [comment]
After running some local tests, it seems to be an issue with firefox 129 and our current cypress version, when upgrading cypress to version 13.13.2, I could at least not detect any further issues

**Comment by walesch-yan** [comment]
I made a pr #1344 for the version upgrade, the tests seem to be working here, still they seem to take around 25 attempts to connect to firefox, I wonder if it would make sense to ensure the correct running of firefox in the workflow before running the tests

**Comment by fabcor-maxiv** [comment]
There is a dedicated GitHub Action fro Cypress: <https://docs.cypress.io/guides/continuous-integration/github-actions>, could it help maybe?

**Comment by walesch-yan** [comment]
Thanks! I will take a look at this and see if we could find a solution for this

**Comment by fabcor-maxiv** [comment]
I guess <https://github.com/mxcube/mxcubeweb/pull/1344> fixed it, so I close the issue.
