### ISSUE TITLE
Pytests fail when using latest mxcubecore (v1.142.0)

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1370]
When running pytest, with latest mxcubecore  (v1.142.0) installed, these tests fail:

```
FAILED test/test_beamline_routes.py::test_beamline_get_all_attribute - AssertionError: assert 31 == 30
FAILED test/test_beamline_routes.py::test_get_beam_info - AssertionError: assert False
FAILED test/test_diffractometer_routes.py::test_get_aperture - AssertionError: assert False
FAILED test/test_diffractometer_routes.py::test_set_aperture - AssertionError: assert 0.001 == 'A10'
```
I started looking into this, it seems these are changes related to resent beam definer changes.

I made an attempt to fix it: https://github.com/elmjag/mxcubeweb/tree/mocked-beam-definer but failed.

I'm trying to do two things on the branch above:

- change mocked beamline to use the beam definer HWOBJs
- update tests to work with API changes

I have trouble figuring out how it supposed to be. @beteva @meguiraun perhaps we can look at this together?

**Comment by beteva** [comment]
Indeed I've changed the testst in mxcubecore, not in mxcubeweb. Mea culpa. Let me do the changes here and will come back to you.

**Comment by beteva** [comment]
@elmjag I've made two PRs - one in mxcubecore, another in mxcubeweb. They should solve the beam size/aperture problem you have 🤞
