### ISSUE TITLE
Docs: installing a development environment

### ISSUE THREAD

**Issue by woutdenolf** [mxcube/mxcube3#1384]
https://mxcubeweb.readthedocs.io/en/latest/dev/environment.html#create-the-mxcubeweb-conda-environment

It mentions this command, but this is not a valid conda command:

```
conda env create -f conda-environment.yml python=3.9

SpecNotFound: Invalid name 'python=3.9', try the format: user/package
```

There is no one-step way of doing this afaik. Hence this open issue: https://github.com/conda/conda/issues/12313.

**Comment by fabcor-maxiv** [comment]
Related but different issue: <https://github.com/mxcube/mxcubeweb/issues/1383>, in this other issue we address the fact that resolving for Python 3.9 (and 3.8, but not 3.10 and 3.11) would fail anyway.

**Comment by marcus-oscarsson** [comment]
Where are we with this, do we recommend people to use conda i.e. doing something like:

```
conda env create --name mxcubeweb python=3.x
conda env update --name mxcubeweb -f conda-environment.yml
```

It seems like @fabcor-maxiv mentioned that one could do it in one go using `micromamba`:
```
micromamba create -f conda-environment.yml 'python==3.8' 
```

I don't really have a strong opinion about it, but there is perhaps something I overlooked with this. It would be nice if we could update the documentation accordingly though :)

**Comment by fabcor-maxiv** [comment]
I still want to investigate this, and I am open to input from others.

I almost always use `micromamba`, I sometimes use `mamba`, and I almost never use `conda`. As far as I know most people use `conda`, so we should aim to find something that works for `conda`.

We could also simply remove this block from the documentation and let it to people to figure it out on their own if they need this. Maybe we should review why we added this block in the first place.

**Comment by marcus-oscarsson** [comment]
Closing as replaced by #1383 and #1410

**Comment by fabcor-maxiv** [comment]
I am going with `conda` and two commands: <https://github.com/mxcube/mxcubeweb/pull/1412>.
