### ISSUE TITLE
Display errors for `PopInputs`

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1404]
We used to display an error message below the input of the `PopInput`. For instance when the user tries to go beyond the limits. It seems like this error message is no longer displayed.

![image](https://github.com/user-attachments/assets/571f5e78-696a-4b90-a0d9-79b6ba733984)

The error is handled on the backend and a ValueError is raised:

![image](https://github.com/user-attachments/assets/a42b5b4d-e512-41e3-819f-8a4202c5f6a2)

I guess one can debate whether this should be 5xx or 4xx error. It should perhaps in my opinion be more a 4xx error as its something we are handling and its an "expected error condition"

**Comment by marcus-oscarsson** [comment]
I will create another issue, for also logging this errors to `user_level_log` so that the user also can see it in the "log component" under the queue.

**Comment by walesch-yan** [comment]
In #1409 this was changed to return a 4xx error. Hence I will close this Issue.
