### ISSUE TITLE
Remove `System log` from UI

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1405]
We would like to propose to remove the `System log` tab/view completely from the UI. It does not really add any useful functionality and we don't want to propagate this sort of information to the UI (at least not here at ESRF). What do the rest of you think of removing this from the UI.

![image](https://github.com/user-attachments/assets/32682c4d-1871-4189-a16b-77aa3e0391b5)

**Comment by marcus-oscarsson** [comment]
@elmjag, @meguiraun @fabcor-maxiv, what do you think ?

**Comment by elmjag** [comment]
I have no idea if this is somehow used by the users. We in software group don't need that page, as we can see the log in other places. I think it's probably fine to remove it.

A more cautious approach is to make it configurable if the tab is visible or not. Say put a new option into `mxcube-web/ui.yaml` `system_log_visible`, with default setting false.

Wait X amount of months. If nobody asks about the missing system log tab, just delete it. If somebody is missing the tab, we add documentation on how to make it visible.

**Comment by marcus-oscarsson** [comment]
I agree that would be a more cautious approach. However we are sure that nobody is using it here, and we actually don't want to propagate this sort of information to the UI. If you guys have a doubt we can make it configurable otherwise Ill suggest to simply remove it

**Comment by meguiraun** [comment]
I rarely use this tab, I usually go and check the log file or a kibana dashboard. I checked with our scientist and they don't use it much.

I am ok with removing it.

**Comment by fabcor-maxiv** [comment]
I do not think I have ever used this.

**Comment by marcus-oscarsson** [comment]
:), Ok I think that settles it. Lets remove it. You can send all complains of it missing to me :)

**Comment by elmjag** [comment]
Yes, remove it!

Try to do it in one commit, then in case we'll need to bring it back, it would be easier :)
