### ISSUE TITLE
Seems like [react-contexify] Context Menu stopped working 

### ISSUE THREAD

**Issue by jbflo** [mxcube/mxcube3#1426]
[react-contexify] Context Menu stopped working on components/Equipment/Harvester.jsx && components/Equipment/PlateManipulator.jsx . 

Maybe in there also components/SampleQueue/CurrentTree.jsx

@marcus-oscarsson  can you check if this the case for the render of  components/SSXChip/SSXChip.jsx

it's like the Context are are not showing at all, or show from a unknown position.  

*** Edited add error Message from the library  ***
![image](https://github.com/user-attachments/assets/8d9e85e1-5e7b-4fa0-83f0-e4373f88adad)

**Comment by marcus-oscarsson** [comment]
Ill have a look, do you have some error in the js-console ?

**Comment by jbflo** [comment]
> Ill have a look, do you have some error in the js-console ?

![image](https://github.com/user-attachments/assets/4500bd78-6f41-4869-bbd4-723056b05aab)

**Comment by jbflo** [comment]
Ubdate react-contexify to 6.0.0 [ latest] fix the issues.
should be fine @marcus-oscarsson.

**Comment by marcus-oscarsson** [comment]
Hm, could it be because of `Vite`, great if the update works
