### ISSUE TITLE
Motor value does not show in ui

### ISSUE THREAD

**Issue by walesch-yan** [mxcube/mxcube3#1433]
After the latest changes the UI does not show the current values of some motors. Only the step input is visible.
![Screenshot from 2024-10-02 15-14-36](https://github.com/user-attachments/assets/5685b037-8fe4-4ff4-9142-b7e8455987d8)![Screenshot from 2024-10-02 15-14-54](https://github.com/user-attachments/assets/4997a1e6-a5d5-4cc9-8e52-fdfeb5ef7f9c)

One exception are the motor fields hidden behind the setting button of sample alignment
![Screenshot from 2024-10-02 15-15-09](https://github.com/user-attachments/assets/7f7b1555-d10a-4354-acca-604e06f65685)

**Comment by axelboc** [comment]
Is that in Chrome, maybe? `flex: none` on the step field should do it.

**Comment by walesch-yan** [comment]
Yes that only happens in Chrome, everything seems fine in firefox
