### ISSUE TITLE
retrieving samples from SC and LIMS Sync

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#1437]
halo,

for these buttons

<img width="244" alt="image" src="https://github.com/user-attachments/assets/d2b636ef-d33b-437b-8908-799c76c1c413">

- the first one displays all the samples present in the sample changer, no matter if the user should see them or not
- the second one displays only the ones the user is supposed to see

Here at MAX IV we dont want the first one, I was thinking on replacing the first one by the second, and have only one button. The equipment tab still displays all the samples.

Any opinion? (I am sure it works like this since a long time ago)

**Comment by axelboc** [comment]
We've also received user feedback recently saying that the "Get samples from SC" button was maybe obsolete.

**Comment by meguiraun** [comment]
https://github.com/mxcube/mxcubeweb/pull/1439

**Comment by marcus-oscarsson** [comment]
Closing :)
