### ISSUE TITLE
Refactor signals

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#146]
The way we are sending the socketio messages is very limited (or better said, messy and cra.xxxx). We need to refactor and:
* use the socketio channels properly, right now everything is sent through the ```hwr_record``` and the client filters according to the signal name
* group several signals together through the same channel, such as the ones related to the movement of a motor, results of task, etc.

**Comment by mguijarr** [comment]
I think this is solved with #166 ?

**Comment by meguiraun** [comment]
yep, we can close this one.
