### ISSUE TITLE
Client retrieve state

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#147]
After the serialization (https://github.com/mxcube/mxcube3/pull/129 and https://github.com/mxcube/mxcube3/pull/137) we changed what we stored in the session, from storing the react state (sent by the client) we store the mxcube.queue hw_obj (done exclusively by the server). The major problem is that the client no longer knows what to do with what is in the session...

**Action**: refactor the client (and probably the object the server returns) so that it takes the state from the session and applies to the interface. For that:
*  [Loading state ](https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/Queue.py#L176): there is a small bug since the ```session.get("queueList")``` will never be ```None```. ```len(session.get("queueList")) == 0``` might be enough, since if the object is empty ```={}``` 
* check the [jsonParser](https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/Queue.py#L732) for an example of how it looks like
* Does not seem to be necessary to store the ```sampleList```
* The client needs to parse that object and create samples, tasks, etc... accordingly
* Whatever the server sends must be independent of the client, I mean, the server does not care about react

This is why I said to implement a workaround and move forward, for a later fix. Instead of implementing the parsing on the client now. Of course, let's discuss about it, we have more fingers&brains now!

**Comment by mguijarr** [comment]
I would say we can close this one? Now we implemented the question to restore Queue... ?

**Comment by meguiraun** [comment]
As it is defined, the client should restore the state, which it does not do now. We can close this one assuming only _state retrieval_, and open a new one for _state apply_?

**Comment by mguijarr** [comment]
Can you confirm this issue is solved with latest queue / state developments ?

**Comment by meguiraun** [comment]
I think that we still have some work to do regarding this issue, basically agree on the architecture. But I agree on closing this one, and open more specific ones as needed (as you suggested)
