### ISSUE TITLE
Timezone error on Ubutun 24 silenced by `login_info` endpoint

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1477]
I've just upgraded to Ubuntu 24 and had to reinstall `mxcubeweb` from scratch. Unfortunately, I couldn't get past the login screen even though I wasn't getting any error. The `login` endpoint would just return 200 with `{ "msg": "" }` and then the subsequent `login_info` request would also return 200 but with `{ "loggedIn": False }`...

After trying to reinstall from scratch like ten times, with different versions of python, with `pip` instead of `poetry`, etc., we found that the problem came from an error in `usermanager.login_ingo()` that was getting swallowed by the `try/catch` statement in the [`login_info` endpoint](https://github.com/mxcube/mxcubeweb/blob/develop/mxcubeweb/routes/login.py#L92).

This issue is about refactoring this statement (and/or `usermanager.login_info()`) so unknown errors are not silenced in the future.

---

For information, the error that I faced was thrown when calling [`current_user.to_dict()`](https://github.com/mxcube/mxcubeweb/blob/develop/mxcubeweb/routes/login.py#L92) and had to do with timezones:

```
tzlocal.utils.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: Europe/Paris\nFix the configuration, or set the time zone in a TZ environment variable.\n'
```

My `/etc/timezone` file contained the text `Etc/UTC`. I replaced this text with `Europe/Paris`, to match the target of the `/etc/localtime` symlink, and the error went away. Has anybody else tried to run `mxcubeweb` on Ubuntu 24 yet? If the problem is not isolated, then maybe we'll have to upgrade `tzlocal` or something.

**Comment by walesch-yan** [comment]
As follow up: I just faced the exact same issue after upgrading to Ubuntu 24.
