### ISSUE TITLE
camera image

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#148]
currently [this] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/SampleCentring.py#L76) does not work the same for the mockup and the real md2.  L81, 89, and 90 are needed for the real image.

**Action**: fix, the same code must work no matter the origin of the image. Check what is missing in the content (L102), some king of jpg tag?

**Comment by JieNanMAXIV** [comment]
It worked for the mockup, but not for our MD2. It's due to a bug in our MD2Camera.py, which sent the image name instead of image string. It was fixed by the PR [141](https://github.com/mxcube/mxcube3/pull/141).

**Comment by meguiraun** [comment]
thanks Jie, created a PR https://github.com/mxcube/mxcube3/pull/149 for the server side
