### ISSUE TITLE
Remove dead code regarding saving app state to disk

### ISSUE THREAD

**Issue by mockoocy** [mxcube/mxcube3#1480]
Issue inspired by this comment
_Originally posted by @elmjag in https://github.com/mxcube/mxcubeweb/pull/1466#discussion_r1820288184_
            
The [`MXCUBEApplication.save_settings`](https://github.com/mxcube/mxcubeweb/blob/05a2ca6f3865b09601cc579546a571b85a8b8490/mxcubeweb/app.py#L496C1-L502C7) function nor the file (`/tmp/stored-mxcube-session.json`) created by are not referenced anywhere in the code. It is probably safe to remove.

**Comment by marcus-oscarsson** [comment]
You can remove it :)
