### ISSUE TITLE
SQL error when trying v4.231.0 or later

### ISSUE THREAD

**Issue by laispc** [mxcube/mxcube3#1494]
Hi,

I was trying to run some of the latest versions of mxcubeweb to check if a potential bug was already fixed (to be commented later in another issue), but I could not get them running.

From a fresh installed conda env, I tried, for example, mxcubeweb v4.231.0 + mxcubecore v1.188.0 (as fixed in mxcubeweb poetry.lock), and some other combinations of the latest tags and develop branches. However, I am always getting an SQL error when trying to login as `idtest0` + any password (see attached txt file).

Any idea about the cause? And am I using the correct core version? Thanks!

[mxcubeweb_sql_error.txt](https://github.com/user-attachments/files/17735503/mxcubeweb_sql_error.txt)

**Comment by marcus-oscarsson** [comment]
Ahh, yes its beause the database schema have been updated and your temporary database still has the old schema. Simply remove /tmp/mxcube-user.db and it should work :)

**Comment by laispc** [comment]
@marcus-oscarsson thanks a lot! File removed, and it now works. :sparkles:
