### ISSUE TITLE
Sample View image not displayed for mockup config

### ISSUE THREAD

**Issue by laispc** [mxcube/mxcube3#1495]
Hi,

Probably a simple issue/doubt: when running the mockup config (mxcubeweb/demo), the example video image `mxcube_sample_snapshot.jpeg` set in `md_camera.xml` is never displayed on the UI (the sample view widget is always black).

On the core side (`MDCameraMockup.py`), the image path is found and the image is emitted (with the `imageReceived` signal), but it's not handled by `sampleview.py on the Web side (e.g., method `_new_frame_received()` is never called apparently). No error message appears in the log regarding this.

Is this the expected behavior? Does tha camera have to be enabled manually? Would be nice to have the image showing, so we can have a base for new camera implementations (which is what I am trying to do :grin: ). Thanks!

**Comment by walesch-yan** [comment]
It could be that `ffmpeg` is not correctly installed, if I remember correctly it is not a direct dependency of `mxcubeweb`, however the `video-streamer`. Could you try installing `ffmpeg`, re-run the mockup-server and see if that resolves the issue?

**Comment by laispc** [comment]
Version used: mxcubeweb v4.231.0 + core v1.188.0 (forgot to include in the description).

**Comment by laispc** [comment]
Great, @walesch-yan , thanks a lot! I installed `ffmpeg` with pip and apt (in Ubuntu) and now I have an image on the UI. :fireworks: 

The funny thing for me is that the image I get is the `fakeimg.jpg` and not the `mxcube_sample_snapshot.jpeg`. I am trying to understand why. :laughing:

**Comment by walesch-yan** [comment]
You're welcome!:) 
That is actually the way it is intended, the mockup version uses the 'TestCamera' from `video-streamer`, which will always only use the `fakeimg.jpg`. The `mxcube_sample_snapshot.jpg` is used for the snapshot routinein the mockup, i.e. if you press the `Take Snapshot` button on the mockup UI, your browser will download that image (overlayed with the shapes you drew on the `SampleView`)

**Comment by walesch-yan** [comment]
If you want to change the image that is displayed on the mockup you would have to clone the mxube/video-streamer repository change the picture in here and from the root of the repository use `pip install -e .`

**Comment by axelboc** [comment]
> It could be that `ffmpeg` is not correctly installed, if I remember correctly it is not a direct dependency of `mxcubeweb`, however the `video-streamer`. Could you try installing `ffmpeg`, re-run the mockup-server and see if that resolves the issue?

I suggest we document this, and the part about which image is used for display/snapshot, somewhere. I couldn't remember it either when I recently re-installed MXCuBE.

**Comment by marcus-oscarsson** [comment]
I would advocate adding `ffmpeg` as a dependency to the `mxcubeweb` `conda-environment.yml` ? and yes documenting would also be good :)

**Comment by Baokangwen** [comment]
> It could be that `ffmpeg` is not correctly installed, if I remember correctly it is not a direct dependency of `mxcubeweb`, however the `video-streamer`. Could you try installing `ffmpeg`, re-run the mockup-server and see if that resolves the issue?

I'm in the same situation，my md2‘s video image is never displayed on the UI.
How should I do it？

**Comment by walesch-yan** [comment]
> I'm in the same situation，my md2‘s video image is never displayed on the UI. How should I do it？

Sorry for the late reply, due to the winter holidays, I did not see your question for some time. Do you still face the same issue? If yes, could you see if `ffmpeg` is installed on your system using the `ffmpeg -version` command?

**Comment by Baokangwen** [comment]
my computer system is centos7,ffmpeg cannot installed on your system.
the sample view widget is always black
UI can't get this md2's img data, just like the picture shows, I don't know how to fix this.
![Image](https://github.com/user-attachments/assets/7c571a59-d05d-4a34-b147-bfde7f0a1975)

**Comment by walesch-yan** [comment]
> my computer system is centos7,ffmpeg cannot installed on your system.
the sample view widget is always black
UI can't get this md2's img data, just like the picture shows, I don't know how to fix this.

If you cannot install `ffmpeg`, you cannot use the [video-streamer](https://github.com/mxcube/video-streamer). MXCuBE-web still has the alternativ `HttpStreamer`, which directly connects to the camera HWR. To enable the server to use it, you need to modify your `server.yaml` file.

In `server.yaml` look for this section:

![Image](https://github.com/user-attachments/assets/a31db53c-2b51-4aa8-b04c-4fda716ef43d)

here change `VIDEO_FORMAT` to `MJPEG` or `HTTP` and the `VIDEO_URL` to an empty string (the code is actually checking for these parameters and changes automatically to `video-streamer` mode with the default values). In the end your change should look like this:

![Image](https://github.com/user-attachments/assets/dc231e4c-5f12-4ad1-b512-9fb94c48d311)

Let us know if this works for you!

**Comment by Baokangwen** [comment]
@walesch-yan 
Thank you very much.
SET:VIDEO_FORMAT: HTTP,the picture has been successfully displayed.

**Comment by Baokangwen** [comment]
Dear @walesch-yan 
I encountered an issue when moving the detector by a specified distance. I input the value in millimeters, but during the movement, the frontend displays the value in micrometers. However, after refreshing the page, it returns to millimeters. I suspect that the frontend and backend data are not being synchronized properly. I have verified that the unit conversion in both the frontend and backend is correct.

The picture is shown below.

![Image](https://github.com/user-attachments/assets/ef98e9ef-1d6a-4f4b-bde7-7d1dc1d71781)

![Image](https://github.com/user-attachments/assets/27e61ede-c412-4cb8-a35d-48489626871f)

Do you have any good testing methods to troubleshoot this issue?

**Comment by walesch-yan** [comment]
> [@walesch-yan](https://github.com/walesch-yan) Thank you very much. SET:VIDEO_FORMAT: HTTP,the picture has been successfully displayed.

Happy to help!



> Dear [@walesch-yan](https://github.com/walesch-yan) I encountered an issue when moving the detector by a specified distance. I input the value in millimeters, but during the movement, the frontend displays the value in micrometers. However, after refreshing the page, it returns to millimeters. I suspect that the frontend and backend data are not being synchronized properly. I have verified that the unit conversion in both the frontend and backend is correct.
> 
> The picture is shown below.
> 
> ![Image](https://github.com/user-attachments/assets/ef98e9ef-1d6a-4f4b-bde7-7d1dc1d71781)
> 
> ![Image](https://github.com/user-attachments/assets/27e61ede-c412-4cb8-a35d-48489626871f)
> 
> Do you have any good testing methods to troubleshoot this issue?

@Baokangwen I cannot think of a direct solution or method to test this, as I would need to investigate it a little more, could you maybe open another issue for it? As it is not linked to the sample view image and a new open issue would help to focus attention to the problem.
