### ISSUE TITLE
Local/remote mode

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#15]
Ability to gain experiment control from a ~local gui over a remote user, it is not mandatory in the beginning, however it will be required at long term so the initial development must take this into account and an initial environment for this characteristic must be set.

**Comment by mguijarr** [comment]
See PR #333 for progress about this

**Comment by mguijarr** [comment]
#333 has been merged, let's close this one for now - new features/bugs will go to new issues.
