### ISSUE TITLE
Return of the authentication issue. 

### ISSUE THREAD

**Issue by HilbertCorsair** [mxcube/mxcube3#1501]
![Screenshot_2024-11-28_14-38-37](https://github.com/user-attachments/assets/9782a70c-4a87-4aca-9634-bd034453c2ca)
As I recently installed the latest versions of both mxcubeweb and mxcubecore I had to deal withe the login issue opened about 2 weeks ago [here](https://github.com/mxcube/mxcubeweb/issues/1494) 
I was happy to see the quick fix of this problem by deleting the /tmp/mxcube-user.db file. This worked initially. I was able to login and access the demo version of the app. The problem came back however and this time deleting the /tmp/mxcube-user.db file no longer works. It's as if the bug got stronger and is now resistant to the antidote :) . 
Unlike the error pointed out in issue 1494 in my case I do not see a SQL error although the error points to the same line 141 in the usermanager.py file. 
The console only displays a MX3 HWR error : Could not login to LIMS (screenshot attached)
It looks a lot like the previous issue but without the SQL error and removing the /tmp/mxcube-user.db no longer works.

**Comment by HilbertCorsair** [comment]
What I did was : 
1) Pulled the develop branches of both mxcubecore and mxcubeweb
2) Installed the latest versions of both mxcubecore and mxcubeweb
3) I started the app
4) I got the login error, checked the previous issue and deleted the .db file
5) Restarted the app and successfully logged in
6) I switched to different  mxcubecore an mxcubeweb branches to work on some PX1specific HOfiles 
7) I switched back to the develop branches on both repos, cherry picked the commit and opened a pull request 
8) While back on the develop branches I tryed to run the app again 
9) I got the login error
10) I deleted the .db file and restarted the app
11) I got the same loggin error. 

Any comments and suggestions are welcomed !

**Comment by marcus-oscarsson** [comment]
What are the test credentials you are using ?

**Comment by marcus-oscarsson** [comment]
Could you also share your `lims.xml` for the mockups ?

**Comment by HilbertCorsair** [comment]
I am using the usual idtest0 for login with a string for password.
The lims.xml si: 
```
<object class="ISPyBClientMockup">
  <object hwrid="/lims_rest" role="lims_rest"/>
  <ws_root>
    https://your.lims.org
  </ws_root>
  <base_result_url>
    https://your.limsresults.org
  </base_result_url>
  <ws_username></ws_username>
  <ws_password></ws_password>
  <loginType>proposal</loginType>
  <object role="session" href="/session"/>
</object>
```

**Comment by marcus-oscarsson** [comment]
Which version of mxcubeweb and core are you using ?

**Comment by marcus-oscarsson** [comment]
The error you mention above does not seem to correspond to the code in latest develop, are you sure that there is no mismatch somewhere. I checked out the latest develop a few minutes ago and it worked well for me

**Comment by HilbertCorsair** [comment]
I have version mxcubecore v1.194.0 and mxcubeweb v4.234.0 
But I think it is just my local develop branch that has a problem for some reason because I launched the app from a different branch and I noticed I can login.
