### ISSUE TITLE
Socketio client version

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#153]
hi,

In the PR https://github.com/mxcube/mxcube3/pull/139/ the commit https://github.com/mxcube/mxcube3/pull/139/commits/6efd2349129de997e05e6856face1c171d7f8c29 downgraded the socket.io-client version. I know that it was because you could not make it work with lower python libraries, which was fixed by https://github.com/mxcube/mxcube3/pull/140. But the javascript lib version evaded my checks, so it went back to a lower version and it was merged...

Which socket.io-client version are you using? Here we are at 1.4.5

**Comment by mguijarr** [comment]
At the moment we are using 0.9.16 ; I fully agree to upgrade, provided that it works... So if #140 solves
all problems let's go for ^1.4.5...

**Comment by mguijarr** [comment]
Let's close this one since we merged #154
