### ISSUE TITLE
Javascript and React style guide

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#165]
Hello everybody !

We spoke about Javascript and React guidelines on our last meeting, so I looked around a bit and I found one used by Airbnb. I find it really complete and it goes a little bit further than just being a guideline and also provides some best practices. I purpose that we use this one for our project, we maybe have to make some smaller deviations of our own but I think its basically good as it is. I have made a fork for it on the MxCuBE organization so that it will be easier to discuss it and purpose changes. You can find it here : 

[JS and React style guide](https://github.com/mxcube/javascript)

Please let me know what you think,
Cheers !
Marcus

**Comment by bolmsten** [comment]
Hi,

I think this is great, the more we can set a universal style the better!

Best regards Fredrik

**Comment by marcus-oscarsson** [comment]
@bolmsten,

Yeah I really agree and they have made an excellent work of describing each rule. The only thing we need to do is to add what we consider is missing and maybe change some smaller things.

There are actually only three things that I would maybe like to change,
 
1. I prefer to use spaces after parenthesis in conditionals like if ( expr ) {}, 
    the style guide say no to that i.e use if(expr){}.

2. I prefer to use double quotes " instead of ' for everything since it makes life easier, they use single
    quotes for JS and double for JSX.

3. I prefer as short filenames as possible, with underscores to separate terms. They name the file
    after the class it exports (Like Java).

Point three is more important to me than one and two. However, these points does not really matter to much to me in the end. So its basically up to what you guys think ?

Cheers,
Marcus

**Comment by bolmsten** [comment]
@marcus-oscarsson 

I have some initial feedback on the new linting rules:

1. Do we need to force proptypes? I see that this could be valuable for the smaller components but it adds a lot of overhead in the containers. 

2. Regarding naming, I prefer to use the AirBnB standard of:

"22.2 Use camelCase when naming objects, functions, and instances. eslint: camelcase jscs: requireCamelCaseOrUpperCaseIdentifiers"

"22.3 Use PascalCase only when naming constructors or classes. eslint: new-cap jscs: requireCapitalizedConstructors"

but this can of course be discussed. 


I will get back to you if I have more thoughts.

**Comment by bolmsten** [comment]
We can also use eslint --fix to remove a lot of the errors for free

**Comment by bolmsten** [comment]
I also don't like comma-dangle and want to change this to the opposite

**Comment by marcus-oscarsson** [comment]
I agree with you on proptypes, it's probably not necessary and as you say cumbersome for containers. I don't mind if remove that rule.

I have nor real opinion about the dangling comma, its as you like :).

We can maybe take some time when you guys are here to go trough the eslint config so that it corresponds to what we like to have. If you think its relevant to spend time on that when you are here ?

Marcus

**Comment by mguijarr** [comment]
Just a question: is this discussion finished? Can we close the issue?

**Comment by bolmsten** [comment]
I think so!
