### ISSUE TITLE
`git submodule update` fails

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#169]
`git submodule update` fails because of a missing commit in HardwareObjects submodule,
can someone push the missing commit please ? :)

```
Cloning into 'mxcube3/HardwareObjects'...
remote: Counting objects: 5407, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 5407 (delta 30), reused 5 (delta 5), pack-reused 5357
Receiving objects: 100% (5407/5407), 2.30 MiB | 555.00 KiB/s, done.
Resolving deltas: 100% (3524/3524), done.
Checking connectivity... done.
fatal: reference is not a tree: 2bdf2b105322079d26d283b7e31c6269261001d3
```

**Comment by JieNanMAXIV** [comment]
Done..., see the PR #170

**Comment by mguijarr** [comment]
Thanks for fixing it, in fact the bad submodule reference was introduced by a previous PR about Beamline Setup. Sorry.

**Comment by JieNanMAXIV** [comment]
No problem :) I've been using a local branch recently, so haven't updated very much, but should do it more often.
