### ISSUE TITLE
login id for session should rely on proposal returned from ISPyB instead of user login ID

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#172]

**Comment by hnaalas** [comment]
Salut Matias

could you precise exactly what you mean to do with this ticket? As you know, SOLEIL is very much complicating everything related to login, ISPyB and related, so any serious modifications to the actual scheme might become a catastrophe for us.

Cheers, leo

> On 28 Apr 2016, at 18:13, Matias Guijarro <notifications@github.com> wrote:
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

-
Leonard Chavas
- 
Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex
France
- 
Phone:  +33 169 359 746
Mobile: +33 644 321 614
E-mail: leonard.chavas@synchrotron-soleil.fr
-

**Comment by mguijarr** [comment]
At the moment in MXCuBE 3, the "login id" (individual username -like at MAX IV- or proposal -like at ESRF-) is used to identify a "session". So for example, if a user is logged in on the MXCuBE 3 web
application, and she closes Firefox, then opens Firefox and do the login again, the state of the
application is restored (contrary to what happens with MXCuBE 2.x, where the interface restarts
from fresh). 

The bug to fix identified by this issue is the following: if 2 users or more are working on the same
proposal, each of them would get a different session with current implementation at MAX IV, because
each user has its own username. At ESRF it's not a problem (yet) because users identify themselves
with a proposal account.

The work to do is quite easy: let's always save a session by proposal.

This affects only MXCuBE 3.

**Comment by hnaalas** [comment]
Thanks Matias for the explanation; things are clear now. SOLEIL is the same as ESRF in this regard (proposal numbers).

Cheers, leo

> On 29 Apr 2016, at 16:30, Matias Guijarro <notifications@github.com> wrote:
> 
> At the moment in MXCuBE 3, the "login id" (individual username -like at MAX IV- or proposal -like at ESRF-) is used to identify a "session". So for example, if a user is logged in on the MXCuBE 3 web
> application, and she closes Firefox, then opens Firefox and do the login again, the state of the
> application is restored (contrary to what happens with MXCuBE 2.x, where the interface restarts
> from fresh).
> 
> The bug to fix identified by this issue is the following: if 2 users or more are working on the same
> proposal, each of them would get a different session with current implementation at MAX IV, because
> each user has its own username. At ESRF it's not a problem (yet) because users identify themselves
> with a proposal account.
> 
> The work to do is quite easy: let's always save a session by proposal.
> 
> This affects only MXCuBE 3.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 

-
Leonard Chavas
- 
Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex
France
- 
Phone:  +33 169 359 746
Mobile: +33 644 321 614
E-mail: leonard.chavas@synchrotron-soleil.fr
-

**Comment by mguijarr** [comment]
fixed, see PR #196
