### ISSUE TITLE
mxcube.queue de-serialization when no previous queue has been stored

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#187]
This is an issue to deal with the problem identified by Peter:

    File "/mnt/sync/pkeller/mxcube3/try3/mxcube3/mxcube3/routes/Login.py", line 52, in login
    # mxcube.queue = jsonpickle.decode(session.get("queueList", "{}"))

Although `jsonpickle.decode(session.get("queueList", "{}"))` gives a proper empty dictionary, it
prevents MXCuBE to run.

I guess this is because an empty Queue object has to be returned, not an empty dictionary...

**Comment by meguiraun** [comment]
Should be enough to decode only if session.get("queueList") has data? And let mxcube initialize the mxcube.queue

**Comment by mguijarr** [comment]
Maybe it's good to always set `mxcube.queue` to an empty queue is `session.get("queueList")` is empty, we never know what can happen... I can take care of this issue if you want

**Comment by meguiraun** [comment]
ok, do it as you suggest. Thanks!
