### ISSUE TITLE
Queue structure during execution

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#198]
When the execution of the queue is launched, the internal structure is changed in the ```mxcube.queue```, so that the [serializeQueueToJson] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/Queue.py#L811) returns an empty dict. Once the queue execution is finishes the queue dict goes back to normal. If there is an error during execution the dict will never be back to normal value.

**Comment by marcus-oscarsson** [comment]
I imagine serializeQueueToJson fails because of an exception when the queue is running and thus returns an empty dict. ? This should be resolved by PR #323, which should work fine even if the queue is running. Please take a look and close this

Cheers,
Marcus
