### ISSUE TITLE
XRF Spectra progress and result display

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#22]
- Display the results of the fluorescence analysis.

**Comment by beteva** [comment]
Attention, it should be called XRF (as for X ray fluorescence) and not XFE! This is the scientific standard, which should be followed from the very beginning. i will rename the issue
Antonia

**Comment by meguiraun** [comment]
Thanks for pointing out!

**Comment by mguijarr** [comment]
Thanks Antonia :+1: )
I reopen the issue, though ; I think you closed it by mistake

**Comment by JieNanMAXIV** [comment]
Both are correct. XFE is short for X-ray Fluorescence Emission. It has been called XFE Spectrum in MXCuBE for both v1 and v2.

**Comment by beteva** [comment]
Yes, but when we published an article in 2009 in the Journal of Applied Crystallography (kk5040), the referee insisted on XRF spectra, so I believe it should really follow this name. MXCuBE v1 was before the article and v2 is called XRF scan, which is another mistake, as we do not scan anything. I've changed recently in v2 to be XRF spectra.

**Comment by JieNanMAXIV** [comment]
Thanks! I had thought both were correct. Yes, of course we should make it right for version 3 :)
