### ISSUE TITLE
Main menu 

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#232]
Dear all,

We have had some discussions regarding the main menu lately. The menu recently moved from the top to the left, however the top menu is still present with the logout button and user information. 

The top menu as it is right now is taking up to much screen space for the functionality it provides. It  disturbs me somewhat when i work of the sample grid so I propose to integrate it fully with the menu to the left. I just want to make sure that nobody else is currently doing the same ?

Cheers,
Marcus

**Comment by bolmsten** [comment]
Dear @marcus-oscarsson ,

There was a discussion regarding this at the workshop held in Alba in November and it was decided that there needed to be a top menu. 

My suggestion to you would be to make a design proposal for the next meeting at Hamburg and then they can take a new decision regarding design there?

/ Fredrik

**Comment by marcus-oscarsson** [comment]
Dear all,

I believe that we need to be a little be more agile and able to react and change things while we are this early in the development process. There is otherwise a risk that things get in our way and hamper our progress. For us merging, or only having one menu, is important from a design and usability perspective when we develop the prototype (since the menu is such a evident part of the application). I would like to avoid to make a prototype with the top menu since I think it would have a negative impact.

Also we need to able to change and develop ideas without having workshop meetings. Having to wait several months before we can start implementation or develop an idea is less than ideal. I understand that a different approach can be taken when the state of the application have stabilized. 

I also understand that alot of "new" changes can be tough for you guys to handle right now, when you are on such a tight schedule. 

I will give it a go (since its a minor thing work-wise), ill make a PR when its done if you merge (or reject) before a decision have been taken at the  workshop is entirely up to you.

Cheers,
Marcus

**Comment by amilan** [comment]
Hi Marcus, 
I agree with you in the fact that we need to be more Agile, and if you permit me, I will also add more Lean. There is a big difference between being agile and develop whatever we (as a development team) think it’s most convenient at any moment without the acceptance of our product owners, therefore I'm writing a separated email to continue with this discussion between the development team. That email it’s going to be quite large and I’m sure it will trigger some friendly discussions, so I think it’s better to move it to a private thread.
In any case, and just to clarify my position, I think it’s really good for the project that everyone adds new ideas and try to improve things, but keeping in mind that we, as a development team, don’t have the final decision to accept them.

And said that, I can only thank you for your effort trying to add value to the project.

Cheers,
Antonio.

**Comment by marcus-oscarsson** [comment]
Hello all

I hope your enjoying your free Monday ! :) I considered this issue handled by now, so Ill close it

Thanks,
Marcus
