### ISSUE TITLE
Sample view page layout is weird

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#234]
Latest code gives the following layout in sample view page, when tested on ID30A3 (ESRF beamline),
and I noticed I have the same layout when running with mockup objects:

![bad_layout](https://cloud.githubusercontent.com/assets/2834952/15749780/ea654e36-28e3-11e6-8b56-20f0500715fa.png)

As you can see, the video size is smaller than it used to be and the icons bar that is normally
under the video is in the middle.

Any idea what's wrong ?

**Comment by bolmsten** [comment]
@mguijarr 

It might be that you do not return all that is needed form the initialstatus call, I suspect that you could be missing the zoom parameter.

For the mockups we will upload a fix to this.

**Comment by meguiraun** [comment]
The problem is that the Zoom mockup fails because it does not have ```getState()``` method

**Comment by mguijarr** [comment]
Ok - I can add it if you want ? Or you do it ? As you prefer

**Comment by meguiraun** [comment]
pr the ridiculously fix into 2.2... do you need in 2.1 as well?

**Comment by mguijarr** [comment]
It would be perfect. 

Do not forget that we need to update the HardwareObjects submodule for MXCuBE 3 too. So if
someone clones the repository he will get a working version.
