### ISSUE TITLE
Data collection:Mesh

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#24]
- Ability to configure a Mesh data collection and add it to the queue.
- Display the results of the data collection.

**Comment by amilan** [comment]
This issue was split into several other issues. Does Github allow to set up parent issues? Because in that case, this one could be set as parent of the others.

**Comment by marcus-oscarsson** [comment]
There is now the possibility to draw, configure and add a mesh scan to the queue ( introduced in #504  ), there is a separate issue for the results #405. So closing this one.
