### ISSUE TITLE
Code style: Case

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#248]
Hey everybody,

Its not a major issue and I realize that I might seem a bit picky, I recently commented on upper and lower camel case in a previous PR. It seems like we are currently mixing lower and upper camelcase in variable and property names. Its not super important to me which one we use long as we are consistent. Tough I strongly prefer lower camel case in variable names and properties since this is basically the standard convention used in most languages today.

We might need an additional  discussion on how to handle the values that are sent from the server since these many cases are sent with _.

What do you think ?

Marcus

**Comment by mguijarr** [comment]
We would like to have lower camel case.
