### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#265]
Installation procedure has to be improved.

TO DO:
- remove dependencies/devDependencies => dependencies

**Comment by bolmsten** [comment]
It this issue solved by the docker that Antonio created?

**Comment by mguijarr** [comment]
I do not think so - I do not think we will deploy mxcube with docker? Since it needs to access to the beamline equipments, I am afraid it would make things more difficult and less efficient in term of performance within a docker container. I have no experience with docker so please tell me if you disagree.

In anyways, I created this issue during last MXCuBE meeting when people were struggling with MXCuBE 3 development environment installation. I am not sure we are compatible with most recent versions of npm? I noticed it may help if we do not make the distinguish between dependencies and devDependencies...

**Comment by bolmsten** [comment]
Okay I will have to look into the difference between dependencies and devDependencies, at the moment I think we mix without knowing why. 

Regarding docker I will leave this for @amilan.

**Comment by mguijarr** [comment]
Ok. Thanks Frederik.

**Comment by mguijarr** [comment]
I think our installation problems can all be solved by switching from `npm` to [yarn](https://yarnpkg.com/). AFAIK it is compatible with all features supported by `npm` and uses the same  `package.json`.
This project is quite new but it seems to be very well appreciated (17.000+ stars on github !) I will give it a try soon and see if it makes installing the development environment for MXCuBE 3 faster and more predictable.
It can also be an exercise to upgrade some of our dependencies...

**Comment by bolmsten** [comment]
Bixente was here on visit and for him we used docker to set up the development enviroment. It worked so good that I have now started to run mxcube only through docker as well.

**Comment by mguijarr** [comment]
I think we are talking about 2 different things.

The docker image is perfect for someone to be able to get MXCuBE 3 running very quickly, and it is even possible to do some development as you are doing it now. So far so good.

That said, someone has to set up the development environment (at least when creating the docker image...), and the packages have to be installed. For this task, I think we would be better served by this new tool -yarn- compared to npm.

I do not know Docker very much, I know everybody is very fond of it so it's probably very good. But it seems a bit overkill to have to run MXCuBE 3 within a lightweight virtual machine thing just because dependencies cannot be properly installed using the normal way. Or maybe I am missing something ?

**Comment by mguijarr** [comment]
In fact we should have a better look at devDependencies & dependencies, to make sure we do not include unnecessary files in our bundles

**Comment by meguiraun** [comment]
Mmmm, I understand that this issue is more npm packaging/bundling related. Your proposed pr is lacking the `npm run build` which will make the full/final installation. But perhaps I am misunderstanding something in this issue.

**Comment by marcus-oscarsson** [comment]
I think its a mix between installation related topics, It seems like the original intent was to discuss the general installation procedure. So this script was an attempt to solve that, it can of course be improved maybe by adding build option. I wanted to solve the basic problem to get everything up and running from scratch.

**Comment by marcus-oscarsson** [comment]
I think we can close this issue now, we have the docker and the installation script that I made.
