### ISSUE TITLE
Demo release

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#269]
In order to facilitate the testing we could build and freeze a release that only contains python code and precompiled javascript. In this way people do not need to mess with npm, only the braves will go to npm...

What do you think?

**Comment by mguijarr** [comment]
I agree but I do not consider we can make a demo release yet : people will get hands on it whereas it's not ready yet. I would be happy to do so in a few months (maybe after September milestones ?)

**Comment by mguijarr** [comment]
Antonio released the [docker container](https://hub.docker.com/r/amilan/mxcube_web/) for MXCuBE 3.
