### ISSUE TITLE
Editor Config

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#280]
I purpose that we create something like this  http://editorconfig.org/ and put in the root folder

This will help a lot when developing new code.

**Comment by mguijarr** [comment]
Sorry for the long delay - I took a quick look at editorconfig.org, I have nothing against adding .editorconfig files to the project.

Feel free to add them if you find it useful.

Are you using Editor Config already for other projects ?

**Comment by mguijarr** [comment]
No news - I close this.
