### ISSUE TITLE
Cant test with latest master, wrong version of hardware objects ?

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#309]
Dear all,

I tried to test my latest development against the latest master but I cant seem to get it to work. I thought that it might be because of incompatible versions of hardware objects. So i started to look into it ! 

I have been using hardware objects 2.2 because it was as I understood it what you are using ?. There are two commits from you guys on the master branch more recent than 2.2. So I tried to use master instead but it did not change anything. I even tried to cherry-pick your commits from master into 2.2, with no success. So which version of hardware objects are you using ? Maybe having the right one will resolve the problems I'm experiencing. Or its perhaps some configuration that I'm unaware of ?

So here is what I get using latest master of mxcube3 and hardware objects 2.2.

I cant center and I get the following message:

`    Error: Server refused to add point`

A centered positions is sometimes added when I've tried to center and then refresh the page. Saving the position takes ages but works, if you have some patience :). Then adding a task is not possible because server refused to add to the queue, giving me:

```
      File "/home/oscarsso/projects/mxcube/mxcube3/mxcube3/routes/Queue.py", line 722, in add_method
    return add_data_collection(node_id)
  File "/home/oscarsso/projects/mxcube/mxcube3/mxcube3/routes/Queue.py", line 675, in add_data_collection
    col_node.acquisitions[0].acquisition_parameters.centred_position = qmo.CentredPosition(cpos['motorPositions'])
KeyError: 'motorPositions'
```
I started to debug it a bit but it seems like I'm either missing some commits or not having the right version of something so I prefer to ask you before i dig any deeper :). 

Thanks,
Marcus

**Comment by meguiraun** [comment]
sorry marcus, consequences of the pep8 I guess...

see #307, motorPositions -> motor_positions

**Comment by marcus-oscarsson** [comment]
Hey Mikel !

Not sure that's the problem, Ive tried to reset the branch to the commit before that but it does
not change anything.  Ive tried resting to d8f5522 ( Merge pull request #306 ... ) which works better
but its impossible to save the centered position, the option is not present in the context menu.

Does the latest master work for you ?, which version of hardware objects are you using ?

Cheers,
Marcus

**Comment by marcus-oscarsson** [comment]
Infact it does work in d8f5522, it was just me who did not save a sample.

**Comment by marcus-oscarsson** [comment]
Looking into more in detail, the latest commit that work for me is 7b523 (do not move if not ready, and send back 406).

**Comment by meguiraun** [comment]
Hej Marcus, in order to be able to save a point you need to mount a sample before.
However there was a bug (see #311) when adding a task to a sample.
We are using 2.2.

**Comment by marcus-oscarsson** [comment]
Hey again,

Thanks for helping me out to find the problem :)

The first problem is to add a centered position I cant even get a centered position to save. Just a cross that follows the mouse nothing happens when you click. Ill take a look at #311 in the meantime, because there seems to be problem when adding a task as well. 

I know that we need to add a sample :), I forgot once as I stated above but I since then I have done the tests with a sample mounted. I used git bisect which tells me that there is something wrong in commit 
c7b3656, part of PR #303. I dont really know what though so it would be great if you have some ideas :)

I noticed some commits that are in master but not in 2.2 of the HardwareObjects, so i started to wonder. So 2.2 it is :)

Tricky, this one,
Cheers,
Marcus

**Comment by marcus-oscarsson** [comment]
Hi,

I merged #311 and that seems to solve the problem with adding tasks. However its still not possible
to add centered positions.

M

**Comment by meguiraun** [comment]
there is an issue because ```stateChanged```signal is missing in [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/signals.py#L22). However it is not enough, since it only allows adding one centring point, the following centrings does not work.

Gonna have a look at it

**Comment by marcus-oscarsson** [comment]
That's great Mikel !

Ive been trying to find the source of the problem, but I think its best left to you who knows all the details :).

Thanks,
M

**Comment by marcus-oscarsson** [comment]
Good morning !

Thanks for the great work Mikel, it seems work with PR #314.

Cheers !
Marcus

**Comment by meguiraun** [comment]
Great that it works now!

**Comment by mguijarr** [comment]
Thanks Mikel :)
