### ISSUE TITLE
Updating a task does not update path in queue summary correctly

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#315]
Hi,

Doing my latest tests I noticed some smaller glitches:
- Changing the path works but a / is missing at the end.
- Using the mouse to select path and prefix text moves the entire task (we currently have to use the keyboard to select text)

Another minor remark, Edit is maybe a better text for the button instead of Change ?

Marcus

**Comment by mguijarr** [comment]
What is the status of this issue ? Any news ?

**Comment by marcus-oscarsson** [comment]
Selecting text is now possible but there is still a / missing for the sub directory in the File Path box
