### ISSUE TITLE
React Issues in SampleGrid

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#317]
@marcus-oscarsson 

When I go to the samplegrid I get: 

main.js:11321 Warning: Failed propType: Required prop `title` was not specified in `DropdownButton`. Check the render method of `SampleGridContainer`.
Warning: Failed propType: Required prop `toggleActiveItem` was not specified in `SampleGrid`. Check the render method of `SampleGridContainer`.
Warning: Unsupported style property margin-bottom. Did you mean marginBottom?
......

I can fix it but I know that you are working with this component so maybe it is easier for you?

**Comment by marcus-oscarsson** [comment]
Hey Fredrik,

Yes I noticed this to, I though Id make a separate PR with those fixes later since its not really blocking.
Ill take care of that after I have finished the first  refactoring of the queue, I'm currently taking care of the sample and queue IDs :).

Thanks,
Marcus

**Comment by marcus-oscarsson** [comment]
Fixed by #319
