### ISSUE TITLE
redis security

### ISSUE THREAD

**Issue by pkeller** [mxcube/mxcube3#321]
I have just read about a nasty Linux trojan that uses redis servers without passwords to download bitcoin miners and spread itself around a network. Something to consider when we move to real deployment of mxcube3. More details:

[Linux.Lady.1](http://vms.drweb.com/virus/?_is=1&i=8400823)
[Linux malware? That'll never happen. Ok, just this once then](http://www.theregister.co.uk/2016/08/11/linux_malware_never_ok_just_this_once_then_if_we_must/)

Regards,
Peter.

**Comment by marcus-oscarsson** [comment]
Thanks Peter, 

That's definitely good to be aware of.

Regards,
Marcus

**Comment by mguijarr** [comment]
Thanks for the information.

Normally the redis server is running inside the firewall, it is not exposed on the internet directly so it minimizes the risk of malware infection. At least if it happens it means the whole site is compromised !

The safe bet is probably to use a password for real deployment.

PS: I like the fact this trojan is written in Go ;) Those days it's hard to chose between Go and Rust, both languages are very appealing for future developments...

**Comment by mguijarr** [comment]
I propose to close this one for now - we have been warned.
