### ISSUE TITLE
[Queue] cannot retrieve entry for a given model

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#331]
executing `qutils.get_entry(id)` does not returns the corresponding entry, when it is not a sample model.

For a queue that contains a sample, dc, and char I get the following (printed after the addition of the task):
```
(<Sample object at 0x36a1d50>, <queue_entry.SampleQueueEntry object at 0x36a1bd0>)
(<TaskGroup object at 0x3841d10>, None)
(<Characterisation object at 0x3841e50>, None)
(<TaskGroup object at 0x38ef450>, None)
(<DataCollection object at 0x38ef150>, None)
``` 

The entries are created correctly, and mapped to their corresponding model, i.e. `entry.get_data_model()` returns the correct model.

I also tried to call directly `mxcube.queue.queue_hwobj.get_entry_with_model(a_model)` with the same result.

Does anyone have a clue about what I am doing wrong?

thanks

**Comment by marcus-oscarsson** [comment]
The entries are probably no yet added to the queue, so get_entry_with_model will return None.

entry.get_data_model will return the model for that node. get_entry_with_model starts at the root of the queue and iterates over all entries and will return None if the entry is not in the queue. 

So get_entry will only work for entries that are in the queue. Did you call enqueue with the corresponding entries ?

If the entries should be in the queue make sure that you are calling enqueue. If not you have to keep track of the entries with some other method.

Marcus

**Comment by meguiraun** [comment]
I think they are in the queue already, see [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/qutils.py#L468) and [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/qutils.py#L430)

I am with the master code, I still have not added anything extra for the char

**Comment by marcus-oscarsson** [comment]
How are you calling it, in which context ?. Could you show me the code were you encounter the problem ?

**Comment by meguiraun** [comment]
Sorry for the confusion, the code in master is working, I have just added the following changes:

[here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/qutils.py#L480) I link the signal `queue.connect(queue, 'child_added', add_diffraction_plan)` rigth before the return.

and this method:
```python
def add_diffraction_plan(*args):
    print 'a child has been added', args[1],'    at parent  ', args[0]
    child_model = args[1]
    if isinstance(child_model, qmo.DataCollection):
        # then, check if it has entry
        print 'THIS IS A DATA COLLECTION, with (model, entry):  ',child_model._node_id, get_entry(child_model._node_id)
```
For comparison also do this print [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/qutils.py#L288)
```python
if item_t == "DataCollection"
    node_id = add_data_collection(sample_node_id, item)
    print 'DC ADDED, (model, entry): ',node_id, get_entry(node_id)
```

And I get:
```
a child has been added <DataCollection object at 0x312a290>     at parent   <TaskGroup object at 0x312a610>
THIS IS A DATA COLLECTION, with (model, entry):   3 (<DataCollection object at 0x312a290>, None)
DC ADDED, (model, entry):  3 (<DataCollection object at 0x312a290>, <queue_entry.DataCollectionQueueEntry object at 0x3200350>)
```

The `get_entry` does not work inside my new method.

**Comment by marcus-oscarsson** [comment]
So its as I said but the scenario is a bit tricky :). So what happens is the following we call add_child on the QueueModel object and this method emits "child_added". You have connected the handler add_diffraction_plan to this signal. 

However only the model is created and not the entry itself, that's the problem we would like to solve. There is not yet an entry for model so we cant ask the QueueManager to give us the entry with the corresponding model, that's why get_node will return None for the entry. 

What we need to do is to create a QueueEntry for the DataCollection  in add_diffracrtion_plan, something like this:

```
def add_child_cb(parent, child):
    if isinstance(model, qmo.DataCollection):
        # The parent is already in the queue so we can ask for that entry !
        parent_model, parent_entry = get_entry(parnet._node_id)

        # Create a new entry for the new child, in this case a data collection
        dc_entry = qe.DataCollectionQueueEntry(PMock(), child)

        # Add the entry to the same task group as the characterisation itself
        parent_entry.enqueue(dc_entry)

        # Finally enable it, perhaps not necessary
        enable_entry(child._node_id, True)

        # Tell client that we added a new entry for the diffraction plan
        # socketio.emit('queue', msg, namespace='/hwr')
```

Let me know if something is unclear

**Comment by meguiraun** [comment]
My idea was to check if a datacollection model has been created without a corresponding entry, if so, do something like the code you proposed. But I am not at this point, I have not executed any characterisation which would (hopefully) give a diff plan.

The problem I am facing is different,  the entry is already created [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/qutils.py#L393) and the prints I did correspond to the creation of a single datacollection, done from the interface, see object id. I need to check prior creation of the entry if it has already been created (as it will be if it comes from a user adding directly a datacollection), at that point I found this issue.

I am not sure if we are talking about the same...??

**Comment by marcus-oscarsson** [comment]
Hey again

The only problem is that the we don't know when the "child_added" handler is called, this depends on the implementation of the signal subsystem. So we can never know if a model have an entry or not in the child_added handler. Basically the handler is called before the entries are enqueue by the add_data_collection call. So you call add_data_collection, which calls add_child. child_added gets emitted and your handler gets called. The entry is enqueued after that in the add_data_collection function, almost at the end.

So using get_entry in this handler will never work for the child.

We need to  use another way to know if its a diffraction plan or not, one way would be to check the name of the group which should be something like Diffraction Plan. Ill take a look to see if there is a
better way to handle this. Sorry I don't really remember what we put in place for the characterizations at the moment. Let me know if you find another way and Ill look when I get a good moment.

**Comment by marcus-oscarsson** [comment]
If you want you can quickly call me on Skype some time tomorrow and we can go through it if you like.

**Comment by meguiraun** [comment]
mmmm... I see, arghh... Thanks a lot for the clarification!! I will have a look at alternatives and I'll be back.

**Comment by marcus-oscarsson** [comment]
Yeah, its a bit tricky :). I think the best thing to do is to check if its a TaskGroup thats beeing added and if that task group have the name Diffraction Plan. That would mean that we are adding a diffraction plan, its not super elegant but it will work.

**Comment by mguijarr** [comment]
Any news on that?

**Comment by meguiraun** [comment]
we are on this for the char, we can close since the answer was solved.
