### ISSUE TITLE
Filtering redux-persist

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#334]
There is a need to blacklist in more detail then a whole reducer. A example is sampleview, a lot of things in that reducer should be in sync with slave but pixelsPerMm is calculated for each client and should not be synced. 

I have not looked into redux-persist very much but Matias maybe you have a answer on how to do this?

**Comment by mguijarr** [comment]
Yes I will take care of this when I will have some time. 

Basically it's as easy as writing a custom reducer for REHYDRATE action I think.

**Comment by bolmsten** [comment]
The pixelsPerMm is not fixed yet but could be fixed in the same way I was doing with the points

**Comment by mguijarr** [comment]
I am looking at this now... There are 2 aspects:
* `pixelsPerMm(Y|Z)` in the diffractometer object, which depends on the zoom level
* pixelsPerMm in the UI code, used for calculating distances or angles, which depends on the scaling factor
applied to the video image 

The first one doesn't depend on the client.
The second one has to be calculated from the first one when needed. I do not think we already have the feature for calculating distances and angles from points in the video image ?

It seems to me only the first one is kept in the state, which is ok.

So I am going to close this issue.
