### ISSUE TITLE
Mutating the redux state

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#340]
I observed today that some of the new code regarding the queue on the client is mutating the client state, look [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/ui/reducers/queue.js#L184)

A way of testing this is to add some task to a sample and you will notice that according to the log the sample has always had that task. 

We should probably move over to immutable js or what do you think?

**Comment by mguijarr** [comment]
I think we should be more careful.

What are the implications of moving to immutable.js ? What does it involves in term of time to spend to do it and in term of code ?

I am in the middle of several things, so I did not pay too much attention, but `Array.from` is making a copy so why do you say the state is mutated? (maybe I am overlooking something obvious ?)

**Comment by bolmsten** [comment]
The Array.form is making a shallow copy of arrays with objects. It is very hard to do deep copy in javascript with complex types. 

I think we should fix this issue the ordinary way and have a discussion next time we meet regarding libraries that help with mutating the state.

**Comment by marcus-oscarsson** [comment]
Solved by #343
