### ISSUE TITLE
Running without ldap and lims by default

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#346]
Marcus latest PR was a great first step with getting mxcube and ispyb connected but it is no longer possible to run mxcube out of the box without configuring the ldap and lims xml files. 

I suggest that we go back to mockups for the lims,ldap for the default

**Comment by marcus-oscarsson** [comment]
Hey !

Its simply a matter of the default configuration that we would like to provide. I wanted to provide a configuration that was working with LIMS with the PR I made. Your right that its maybe makes more sense
to use the mockup versions by default.

Marcus

**Comment by mguijarr** [comment]
+1 on going back to mockups for lims and ldap by default
