### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#353]
As Matias has mentioned the icons need to be changed. 

Some points from ESRF:

- Text would be better than some icons ; in particular for
 'Start auto centring' and 'Start 3-click centring'

- Light: no way to know which is front light and back light.

I like the idea of mixing icons with text but I think it will need to be very short( or very small font-size). Regarding the light maybe we should do a combo-box as in mxcube2

**Comment by mguijarr** [comment]
For centring, maybe we can have a label 'Centring:' in the icons bar, then the two buttons with '3-click' and 'auto' as labels.

**Comment by mguijarr** [comment]
I agree with the combo box for light, as in MXCuBE 2

**Comment by bolmsten** [comment]
I will have a PR on this tomorrow

**Comment by bolmsten** [comment]
Did the new design solve it for now?

**Comment by mguijarr** [comment]
Yes.
