### ISSUE TITLE
Menu not visible in chrome 

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#364]
When adding tasks in chrome I see this:

![screen shot 2016-10-26 at 11 12 55](https://cloud.githubusercontent.com/assets/6403388/19720145/33da2e64-9b6d-11e6-9b0a-aaa4e9ec4fa0.png)

**Comment by mguijarr** [comment]
Hi,

I just downloaded Chrome and tried, and I can't reproduce this.

The version I am using is: 49.0.2623.112 m
 
Which is yours ?

**Comment by bolmsten** [comment]
Version 54.0.2840.71 (64-bit) I will try to check if Mikel is seeing i as well

**Comment by bolmsten** [comment]
Version 54.0.2840.71 (64-bit) I will try to check if Mikel is seeing i as well

**Comment by bolmsten** [comment]
Version 54.0.2840.71 (64-bit) I will try to check if Mikel is seeing i as well

**Comment by bolmsten** [comment]
Version 54.0.2840.71 (64-bit) I will try to check if Mikel is seeing i as well

**Comment by marcus-oscarsson** [comment]
Under which circumstances does this happen, did Mikel also have the problem ?

**Comment by meguiraun** [comment]
hi, it also happens to me. Version 54.0.2840.71 (64-bit)

![image](https://cloud.githubusercontent.com/assets/12758327/20131022/fd27da4e-a65a-11e6-8785-8564c2f9f201.png)

**Comment by marcus-oscarsson** [comment]
Thanks,

Windows or Linux ? any other environment specific things to consider ?. It seems to be that the z-index
is somehow handled differently 

Marcus

**Comment by marcus-oscarsson** [comment]
Should be solved by #380
