### ISSUE TITLE
Samplegrid breaks in chrome after removing filter

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#365]
When adding and removing a filter in chrome I see this:

![screen shot 2016-10-26 at 11 14 40](https://cloud.githubusercontent.com/assets/6403388/19720202/7e1ee974-9b6d-11e6-8617-bd8f7e71a260.png)

**Comment by mguijarr** [comment]
See #376

**Comment by bolmsten** [comment]
Good!
