### ISSUE TITLE
Wrong state of queue if client disconnects at run time

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#366]
If the client disconnects when the queue is running (even for a short while like seconds) it can lose information about a running sample. And be forever in this state:

![screen shot 2016-10-26 at 11 19 17](https://cloud.githubusercontent.com/assets/6403388/19720360/192ddea2-9b6e-11e6-9dcb-ca0d63b3bc6e.png)

**Comment by mguijarr** [comment]
See PR #372
