### ISSUE TITLE
motor signal rate causing long delay

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#381]
https://github.com/mxcube/mxcube3/pull/373 introduced a limit on the number of signals sent per second. However, if there are many signals in a very small period there will be all delayed and the client will still receive signals long after the movement is finished. 

Rough test with our diff: 90deg rotation -> ~10 signals/second, and the movement takes ~1 sec

Could we discard the signals arriving inside the delay interval? So if we have 3 sig/sec as limit the client will only receive 3/4 signals, and all will arrive ~synchronized with the movement.

**Comment by mguijarr** [comment]
Of course it's my mistake - it should be like you suggest here, my intent was to discard those events. We just did a fix, see #383
