### ISSUE TITLE
Sample image too large for screen

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#384]
Hey

The sample image is slightly to big for the screen, at least normal widescreen monitors we have here. Ive tried it on screens ranging from 24 to 32 inches, with resolution 1920x1080. Do you have the same issue ?

Marcus

**Comment by bolmsten** [comment]
No but I know why this could be a issue. When designing the sampleimage I made the choice of letting the hight be auto while the width took 100% of 9/12 of the width of the browser window.

This means that if the width X 9/12 > hight, we have a problem. 

I have no solution for this at the moment. We can discuss what can be done.

**Comment by mguijarr** [comment]
Finally we didn't have time yesterday to really talk about this one - what could we do to fix this issue ? Maybe we need to redesign this part of the UI, without relying on the bootstrap grid ?
Or is there a better idea ?

**Comment by marcus-oscarsson** [comment]
Temporarily solved by allocating less columns in the grid for the video
