### ISSUE TITLE
Saving a new point removes previous point

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#388]
When saving a centred position, the previous centred position is removed.

**Comment by marcus-oscarsson** [comment]
Hey !

It seems to me like that this happens when we are using mockups. It looks like, when taking a close look, like the points are stacked on top of each other. So they are not actually removed but masking each other.

Marcus

**Comment by marcus-oscarsson** [comment]
Only on mockups affected, the positions are added on top on each other !
