### ISSUE TITLE
Manual mount: sample is mandatory

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#389]
Manual mount mode ; 3 click-centring, saving centred position, add task => nothing happens.

There are 2 things, first I do not understand why user should "add" a sample when using manual mount. Probably there is a good reason ? For me, manual mount means "do not care about what is on the gonio
(or not)", I do not understand the logic of having 'samples' here.

If it is important to have samples, then it should not be allowed to centre a position if no sample is "mounted".

**Comment by meguiraun** [comment]
We force the user to add the sample so we have a name/prefix for it (although it can also be automatic), but also as a way to notify the user that now is ok to put the sample on the diff.

For the need of having a sample mounted before being allowed to do a centring, I agree with that.

**Comment by meguiraun** [comment]
#419 prevents from centring if no sample is mounted
