### ISSUE TITLE
HardwareObjects submodule

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#39]
At the moment the HardwareObjects submodule points to commit 96cae8 of the HardwareObjects repository. This commit is from the master branch of MXCuBE 2. I think we should not build MXCuBE 3
on top of the master branch versions of Hardware Objects, since it is unstable and some changes may be untested. 
In particular, I wanted to test latest MXCuBE 3 in "real situation" yesterday but I couldn't because the signature of a function changed in MiniDiff.py in master branch compared to 2.1.
My question is : would you agree to use 2.1 versions of Hardware Objects as our HardwareObjects submodule ?
If you are ok I can make a pull request for this, yesterday evening I created a 2.1 branch in the HardwareObjects repository.

**Comment by JieNanMAXIV** [comment]
Hi Matias,

It’s a good idea. In fact, I am trying to merge with the current version so that I can do a PR of MAXLAB HO. I did have some problems with MiniDiff and also a few other HOs. Since the latest version is not fully tested, I think it’s better that we use a robust version, so that we don’t have to deal with the HO bugs and minimize the dev. risks.

Best,
Jie

**Comment by mguijarr** [comment]
Ok great.

**Comment by IvarsKarpics** [comment]
Hi,
Most likely I created to much changes in master branch. Mostly there where changes to EMBL hwobj, but I also changed AbstractMulticollect (add option to run collection without that loop). In principle right now I am working on interleaved connection, that will ask more changes in AbstractMulticollect and queue_entry. Actually then AbstractMulticollect becomes AbstractCollect and more tasks are given to queue_entry.
Solution to this I will show in the next meeting and then maybe we could decide if people are interested in this, should this be in main branch and so on.

**Comment by mguijarr** [comment]
Ok Ivars - if you feel there are too much changes, maybe you can create a development branch for those features, then merge them back into master once you're happy with it ?
Personally I don't mind if a lot of changes are done in master, since it corresponds to our development branch.
The mistake we made when starting MXCuBE 3 was to rely on master branch of HardwareObjects ; it's easy to fix, we will stay with 2.1 - at some point, 2.1 will be legacy and we will have 2.2 and others... It's easy to change submodule.
I think people will be interested in all your new developments ! It's exciting to see new code coming so fast :)

**Comment by mguijarr** [comment]
See PR #41
