### ISSUE TITLE
Adding data collection from Samples Grid should add a 'Centring' task

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#391]
At the moment, when adding a data collection from the grid, there is no way to associate the task with a centred position. There should be a 'Centring' task, to allow user to specify on which position the data collection will happen.

**Comment by meguiraun** [comment]
I thought that it was solved by #356, when you launch the collection it will not find any centred_pos so it launches the 3click centring. How do you know which are the available centring positions in the sample grid? I think I am missing something.

**Comment by marcus-oscarsson** [comment]
There is for the moment no representation for this in the queue, so we can't see which
centering method that is used without looking in the data collection parameters. 

It seems like that the sample-changer and diffractometer mockups does lacks some functionality
to make this run smoothly without hardware. This should however work on a beamline, it was tested
here at ID30-3. It currently only works with 3-click centering and the option for lucid and x-ray
centering is still not taken into account.

We need to decide whether we would like to do like today, that is have some kind of centering task
or to embed into the collection task.

Cheers !

**Comment by mguijarr** [comment]
So, after discussing this:
- [ ] the lucid and x-ray centering options from tasks __has to be removed__
- [ ] the centering task has to be visible in the queue for the sample
- [ ] x-ray centering has to be added __as a task__ (it is a real data collection, in fact)

**Comment by marcus-oscarsson** [comment]
Hi,

This is a very old issue, so the description have become a bit outdated. There is now the possibility to center a sample before a task is executed (if there is not already a centered position for the task). It works like the SampleCentring task but is integrated into the collection task.

So the issue is solved, it needs to be tested a bit more, Ill close it when the testing is done.
