### ISSUE TITLE
Log messages for MD3

### ISSUE THREAD

**Issue by amilan** [mxcube/mxcube3#397]
**User story**
As a user, I want to see log messages for MD3, so that will give me better feedback of what is going on.

**Comment by beteva** [comment]
Please consider different feedback levels - one for user (only basic messages), one for advanced user or local contact (more detailed  information). Warning and error handling should have the same distinction.

**Comment by amilan** [comment]
Nice addition, but, maybe we can start with something simple and later on add another task to implement this kind of filter?

**Comment by bolmsten** [comment]
Is this done by the #386  that @marcus-oscarsson did?

**Comment by mguijarr** [comment]
I don't know - #386 shows user log messages 'at the right place', ie. next to the task execution panel when MXCuBE is executing a task.
It is more general than just displaying MD3 messages.  I would say, if the MD3 hardware object uses the `user_log` logger (in Python code), then those messages will be displayed (like others).
Maybe there was something specific to the MD3 in this issue ?

**Comment by meguiraun** [comment]
Closing because no one knows exactly what it means. Looks solved...
