### ISSUE TITLE
Draw a grid for a mesh scan

### ISSUE THREAD

**Issue by amilan** [mxcube/mxcube3#403]
**User story**
As a user, I want to be able to draw a grid, so that will allow me to select an area to be scan.

**Acceptance criteria**
Given my application running,  
When I want to run a mesh scan I can draw a grid on the camera view,
Then the grid area is selected to be scanned.

**Comment by beteva** [comment]
Please consider - need to be able to change numbering of the images in the grid drawing, depending on the type of mesh you will do (consecutive lines or zig-zag)
