### ISSUE TITLE
Queue API calls (continuation of #411)

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#415]
Now that PR #411 has been merged, implementation of the solution for the AJAX requests agreed at MAX IV last week has to be done:

* once a call regarding queue operation is made, UI is "blocked" (Queue part is disabled / or there is some busy indicator)
* when the call is finished (ACK reply from server received), the UI is released for user operation

I would say priority is quite high, in order to finish the work started with PR #411.

**Comment by bolmsten** [comment]
I have written this code that should do what we talked about regarding the one AJAX call at a time, please review and see if I have missed something. (It is totally independent and runs in node)

I use recursion and bindings of promises when handling AJAX request. The fetch function and its chain is bound and sent to the safeSend function where it is put on an array. Here I check if the sendStack is active and decide if to activate or not. The sendStack executes the first element of the call stack and then the rest of the promise chain is executed. Last the sendStack functions checks if there is more to be done

```javascript
var calls = []

function safeSend(call) {
	console.log("safeSend")
	calls.push(call);
	calls.push(call); // will be removed in production, only here for testing multiple calls
	if (calls.length === 2) { // will be 1 in production
		sendStack()
	} 
}

function sendStack(){
	console.log("sendStack")
	const call = calls[0];
	call().then((result) => {
		calls.pop();
		console.log("pop off stack")
		if (calls.length !== 0) {
			console.log("next call")
			sendStack()
		}
	});
}




function fetch(url) {
	return new Promise(function(resolve, reject) {
  // do a thing, possibly async, then…
  console.log(url)
  if (false) {
    resolve("Stuff worked!");
  }
  else {
    reject(Error("It broke"));
  }
});
 
}


safeSend(() => fetch("mxcube/api/1.0/").then((result) => console.log(result), (result) => console.log(result)));
```

**Comment by mguijarr** [comment]
If I understand it well, what you propose is the following:
- user does some actions, like moving tasks
- user gets visual feedback instantly (tasks are moved in the queue UI)
- in the background, requests are sent to the server
- a queueing mechanism ensures requests are sent one by one

For me it looks a lot like the optimistic rendering we clearly stated we didn't want during our last
meeting. I thought we decided UI will be unavailable when a request is made, to ensure we don't have 2 or more requests in parallel. That's why I wrote the issue as it is written... Is there a good reason to change what was agreed ?

Coming back to the code you propose:
- I imagine we will have multiple `safeSend` calls, depending on user actions
- so, while the first call is made, the `calls` array will grow
- when the first call is finished, `calls.pop()` will remove the last item of the `calls` array, hence removing one pending call - I think there is something wrong here.

Another thing:
- if one of the requests fails, what happens ? The processing of the calls stack should stop, I think it is handled in your code because the `call().then(...)` in `sendStack` only continues to send requests if the request is successful (as far as I understand), but the `calls` array is not cleared
- Isn't some `.catch()` missing ? To deal with errors (not failed API calls)
 
Sorry if I misunderstood something, my Javascript skills are limited.

**Comment by bolmsten** [comment]
Yes there seems to be a misunderstanding. I will try to answer your points below:

Regarding the first paragraph you wrote regarding the flow and the optimistic rendering my comment is: 

The code I have written has nothing to do with optimistic rendering, it is only a way of pipelining AJAX request. What actions are dispatched in the function before and after the AJAX call is not specified. My idea was to dispatch load before the call and the actions afterwards. 

Regarding the code comments:

You are totally correct that pop() is wrong it should have been shift(), thanks for noticing. Regarding the processing of request fails, we did not discuss this in detail but we can clear the call stack.

**Comment by mguijarr** [comment]
If actions are handled one by one, then there is only one AJAX call to do at a time and there is no need for pipelining... In this case I don't understand why we need this. 

Maybe you can give an example of action to be dispatched before and after, to make it less abstract ?

Regarding requests with response != 200, indeed the call stack should be cleared (except if there is only one call each time in the stack ;))

**Comment by bolmsten** [comment]
Ahh now I understand how you want to solve it. I did not make the connection between showing loading and only a single action being sent at a time. 

The solution I proposed would be overkill because the call array would at most contain a single call.

**Comment by bolmsten** [comment]
It is enough spinner

**Comment by mguijarr** [comment]
I'm glad you understood what I meant. Sorry if it was not clear.
