### ISSUE TITLE
Adding tasks directly on sample in sample grid (continuation of #411)

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#416]
Hey,

It used to be possible to add tasks directly on a sample without adding the sample it self first.
For instance by right clicking selected samples and choosing Add Data Collection. This functionality
is now broken and we need a fix for it. This will ideally work similar to ADD_SAMPLES that is that
the requests to add samples and tasks are bundled into one request instead of one per sample.

Marcus

**Comment by meguiraun** [comment]
see https://github.com/mxcube/mxcube3/pull/434
