### ISSUE TITLE
Optimize initialization calls

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#425]
Currently, the `getInitialStatus` in the general actions (https://github.com/mxcube/mxcube3/blob/master/mxcube3/ui/actions/general.js) does several calls that can be merged into a few, such as motor limits and default parameters.

This issue is to do a bit of cleanup on those, perhaps creating a new API call for those constant initialization parameters

**Comment by mguijarr** [comment]
Thanks Mikel :)

**Comment by meguiraun** [comment]
Beamline moveables are not applied during initialization. I note here since it is related but I am not sure if it is a bug or missing feature. I will take care also.
