### ISSUE TITLE
Motor Values are not applied without pressing "return"

### ISSUE THREAD

**Issue by JieNanMAXIV** [mxcube/mxcube3#429]
On the Data Collection view,  the new value of a motor position is not applied until after pressing "return". It should also be applied when the mouse leaves the input field, or otherwise put back the previous value, which is the real current motor position.  

As it is now, if a user presses somewhere else after changing the motor value (but without pressing return), the new value displayed on the UI is not what the motor has.

**Comment by mguijarr** [comment]
Would it be ok for you if the motor value appears in orange (for example) when it is edited ? This is what we have in MXCuBE 2 today.
If it moves before user press Return, it will be back to green (or another state) automatically, just like it is now.
I think it's important for the user to press Return to tell she really want to move ; I don't like if it is moving automatically when focus is lost, or if it discards user input.

**Comment by mguijarr** [comment]
@JieNanMAXIV  @meguiraun  Any opinion?

**Comment by meguiraun** [comment]
sorry, I missed this one.

What do you mean by: "...  automatically, just like it is now." It is not like that at this moment, if you type a new value and then click out of the motor input, you newly written value remains there (without being sent to the motor). So the user will see a wrong motor position.
What you propose is fine for me, assuming that we reset the field to the current position if you click out.

**Comment by mguijarr** [comment]
Sorry if I was not clear ; I think that, at the moment, when a new value is received the field displays the new value and the state is updated (green, yellow or red...). This is what I meant by 'automatically' updated (= when motor moves).

We will see the first who has time to take this issue and fix it... At least we know what we have to do.

**Comment by meguiraun** [comment]
ahahaha, I see it now. To the backlog!
