### ISSUE TITLE
Documentation as github pages?

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#44]
I was thinking on using the gh_pages branch for the sphinx generated documentation. Specifically for the rest api. Right now the api is documented (ejem ejem, it must be improved) at with several people working on this we need proper documentation.

What do you think? I still need to add usefull docstrings but I you want I can prepare something like the following image and commit to the gh_pages and we see if it serve as doc place.

On the other hand... gh_pages might also serve as the project page, but at this moment it think doc is more important.

![image](https://cloud.githubusercontent.com/assets/12758327/11113279/d50d0604-891b-11e5-9a3f-25870d99de24.png)

**Comment by mguijarr** [comment]
Last time I tried gh_pages (for MXCuBE "official" web site) I find it rather difficult but hopefully some tools exist to assist in displaying documentation from code directly on gh_pages ?

Personally I would recommend using [readthedocs](http://readthedocs.org). It builds the documentation
automatically when code is pushed in the github repository, it makes it searchable on the web etc. it's
really nice.

**Comment by meguiraun** [comment]
Basically you push the output of sphinx into the gh_pages branch, and that is enough. I think that the mxcube site has more features and complexity.

The problem I had is that autodoc imports everything and it fails with our current code... So I manually comment some lines in the routes with the single aim of getting the doc output (and revert back to as it was). So, readthedocs will not work as we have the code now.

**Comment by meguiraun** [comment]
have a look at [this] (http://meguiraun.github.io/mxcube3_doc/)
repo [here] (https://github.com/meguiraun/mxcube3_doc)

(done for testing gh-pages and autodoc)

**Comment by meguiraun** [comment]
in order to add the doc files as gh-pages I need to manually create an empty gh-pages branch first, so no PR for that. Is that ok for you?

**Comment by mguijarr** [comment]
Of course yes :)

**Comment by meguiraun** [comment]
created doc pages. see here
http://mxcube.github.io/mxcube3/
