### ISSUE TITLE
Top bar redrawing

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#445]
Redesign the top bar according to attached image

**Comment by meguiraun** [comment]
![20170120_100427](https://cloud.githubusercontent.com/assets/12758327/22145051/14726902-df00-11e6-944f-636875d1b1f4.jpg)

**Comment by marcus-oscarsson** [comment]
Hey !

It seems like a never ending topic but I thought about something that could be nice for the actuators.
Instead of the button below to do trigger the opposite action, one could display an overlay with radio buttons. One for each action (obviously), its maybe more intuitive and also quite easy to implement. One click extra for the overlay though, but we gain some space ...

Just an idea :)

**Comment by mguijarr** [comment]
We (Antonia and I) don't like an extra click.

**Comment by meguiraun** [comment]
+1 for minimising extra clicks

**Comment by marcus-oscarsson** [comment]
As you guys like, its just that I'm not very happy with the layout if we add a button below like that. I'm not sure that its going to look very nice. Id like to have a clean look and feel for the top bar, so its easy to get the right information. There is going to be quite alot of controls there so there is a small risk that it might look crowded.

Its good to minimize the clicks needed, but we also need to asks our selfs if its something that is accessed frequently enough to be quickly accessible. Its perhaps acceptable to have an extra click to access the safety shutter, as long as its status is visible all the time.

**Comment by beteva** [comment]
Hello,
good move to start the cryo component. Only it  looks a bit strange to me. The annealing is better to be as a part of the beamline actions (as it requires a combination of different equipment, but not at all the cryo temperature). Our scientists asked not only the reading, but also setting the temperature, so the cryo component might need the space you allocate for the annealing to be used for that.
