### ISSUE TITLE
mockup hardware objects xml files

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#45]
As pointed out in discussion from PR #42, a common set of mockup hardware objects has to be integrated within the repository in order to make basic testing much easier (and uniform across institutes).

**Comment by meguiraun** [comment]
Should we add those mockups as a folder within mxcube3? Or a common module (sorry, another module again) for all mxcube?

I would vote for the first choice, less mess for the whole project. We can also raise this discussion in Barcelona's meeting to see if the rest of the people think this as useful for them as it will be for mxcube3 development. (but I would create a folder for mxcube 3 anyway)

**Comment by mguijarr** [comment]
+1 for adding a folder within MXCuBE 3 repository only (at least for now)

**Comment by mguijarr** [comment]
Files have been added, more will come but we can consider this issue to be closed ; feel free to re-open it if you feel there is something to add or a remark
