### ISSUE TITLE
redux dev tools

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#473]
Useful tool I have used to inspect the state of the app:

https://github.com/zalmoxisus/redux-devtools-extension

One just need to change a few lines in `main.jsx`:
```javascript
...
import { createStore, applyMiddleware, compose } from 'redux';
...
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(rootReducer, /* preloadedState, */ composeEnhancers(
    applyMiddleware(thunk, createLogger()), autoRehydrate())
  );
...
```

And then you see this (among some logger etc):
![image](https://cloud.githubusercontent.com/assets/12758327/23116848/1063e434-f74d-11e6-9a50-1ef97728ab5f.png)

**Comment by marcus-oscarsson** [comment]
Thats really nice :)

**Comment by mguijarr** [comment]
Thanks for sharing. I was thinking of exactly the same thing last week, I didn't look on the web but I was saying to myself I should write something like this... It already exists :) Good to know.

**Comment by meguiraun** [comment]
glad you like it, then I think we can close this
