### ISSUE TITLE
isotope-layout problems with NPM V.3

### ISSUE THREAD

**Issue by bolmsten** [mxcube/mxcube3#48]
It seems that Isotope-layout has a problem when run with webpack and NPM V.3,  see 

https://github.com/metafizzy/isotope/issues/979

This will be resolved in the future and all that is needed is to download the latest version of Isotype.

**Comment by mguijarr** [comment]
Are you using npm v3 ? Here I am still running node 0.12.7 with npm 2.11.3

**Comment by bolmsten** [comment]
I was using v3 but I have now changed to 2.14.7 and it works. I was just adding this as a reminder for the future to update Isotope.

**Comment by mguijarr** [comment]
ok thanks !

**Comment by mguijarr** [comment]
I think this is fixed by PR #95
