### ISSUE TITLE
Make all fields properly wired to the server, add missing fields in forms

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#482]
Some fields are missing in the forms. They have to added, and properly wired up to the server.

**Comment by meguiraun** [comment]
* beam_size, detector_distance, roi_mode
* Also overlap but I think this one is already there (to check)

Question:
* `detector_distance` is related to `resolution`: do we allow the change on any of these (and update the other accordingly ala real-time)?
* `roi_mode` selector values are not the same for all of us (I guess), so related to #481 should also give the possible values

**Comment by marcus-oscarsson** [comment]
I've added unit cell and space group from previously missing processing parameters, I think that's the last ones. We need to verify that the parameters are correctly passed and used
