### ISSUE TITLE
Grid: spacing

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#491]
Should positive spacing (horizontal or vertical, it depends on the diffractometer geometry) be forbidden in the grid ? Indeed, the grid is mainly used for meshes/grid scans and people expect this to be done shutterless, as fast as possible. However, if a positive spacing is applied to the grid it should convert in much slower individual data collections to shoot the xtal at the right place.
So, do we keep the current behavior or do we forbid positive spacing ?
Maybe we can remove spacing completely ?

**Comment by marcus-oscarsson** [comment]
Closing, since this feature already have been implemented, up to scientific steering committee to decide if feature should be kept or removed.
