### ISSUE TITLE
energy and resolution in task modals

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#506]
The values of energy and resolution in the task modals do not correspond to the ones applied at the beamline but the default values.

**Comment by meguiraun** [comment]
I have a fix ... but for the old redux-form... I will have a look and try to translate

**Comment by mguijarr** [comment]
Ok Mikel thanks - so I assigned yourself. Do not hesitate to ask if you need help.

**Comment by meguiraun** [comment]
solved by #523
