### ISSUE TITLE
Selecting task path in text box

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#521]
It used to be possible to select the path or parts of the path to manually to for instance copy it.
Something that is no longer possible, It should be possible to select the path or parts of the path
for copying.

Trying to select the text now simply drags the entire task

**Comment by meguiraun** [comment]
mmm, the same happens with the Sample Name in the top of the current queue. possibly related? #517

**Comment by marcus-oscarsson** [comment]
I think its the drag event that is the problem so its likely that also effects the selection of other elements
within the TaskItem.

**Comment by mguijarr** [comment]
What about removing drag and drop ?

**Comment by meguiraun** [comment]
I vote for removing the drag&drop, fix this issue and if our scientist request it bring back the task drag&drop later

**Comment by meguiraun** [comment]
it is back again, possibly due to #574

**Comment by marcus-oscarsson** [comment]
Done by #582
