### ISSUE TITLE
Beam stop

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#542]
* text should be 'In/Out'
* Display sample to beam_stop distance and users can reset the value. What does 'reset' means here?
* More advanced controls? for example?

**Comment by marcus-oscarsson** [comment]
Text should already be IN/OUT, it could depend on hardware object used. There should be an appropriate mapping for the state in ho_mediator/statedefs.py. Ive tested it here and its IN/OUT both on mockups and beamline

**Comment by marcus-oscarsson** [comment]
The beamstop distance is no configurable through a small configuration window attached to the beamstop component. Considering this sovled
