### ISSUE TITLE
Sample grid

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#57]
The sample grid displays available samples from ISPyB or contents of the Sample Changer, and also a "Manually mounted" sample.

Selecting items on this grid is the first step to add samples to be collected to the Queue.

The Sample Grid items show a summary of the sample information, including sample changer
location, protein acronym, data matrix code, etc.
It shows the foreseen data collections to be applied on the sample, or those that already happened with some color code.

**Comment by mguijarr** [comment]
@bolmsten @meguiraun How far are we from having a first implementation of the list of data collections to be applied to a sample ? In our samples list structure when people will add data collection (clicking +Characterization for example), the samples queue should be updated of course but I need to update the sample grid too as it is supposed to show data collections to be applied to the sample. When this is done I am almost finished with this task.

**Comment by meguiraun** [comment]
hi,
Not very far from it... I still need to dig into the existing code and get the correct parameters for the sample as well as for the collections. Now I just do not apply any data to the methods. I would say I am half way ...
However, as far as I understand, you do not need the parameters of the methods, you just need the methods associated to each sample. Am I right? If so, there is a working method (http://0.0.0.0:8081/mxcube/api/v0.1/queue) now that gives you the queue in this form:
```
{
  "3": {
    "QueueId": 3, 
    "SampleId": "1:01", 
    "methods": []
  }, 
  "4": {
    "QueueId": 4, 
    "SampleId": "1:02", 
    "methods": [
      {
        "Name": "Centring", 
        "QueueId": 5
      }, 
      {
        "Name": "Centring", 
        "QueueId": 6
      }, 
      {
        "Name": "DataCollection", 
        "QueueId": 7
      }
    ]
  } ..... and the rest of the samples
```
In any case, you also will need the result of the method (ok, failed, not done...). What I can do is to add first the result of 'is_executed' and/or 'is_collected' methods, and after that PR keep digging into the HO code/parameters. Would that be ok? Anything else you might need?

**Comment by mguijarr** [comment]
Actually I just tried the queue route and this is what I get:

```
{
  "1": {
    "QueueId": 1, 
    "SampleId": "1:01", 
    "methods": [
      {
        "ColId": 4
      }
    ]
  }, 
  "2": {
    "QueueId": 2, 
    "SampleId": "1:02", 
    "methods": [
      {
        "CharacId": 3
      }
    ]
  }
}
```
I don't have "Name" and "QueueId" fields. Maybe I don't have the latest code ?

I am asking myself questions about the queue: at the moment each operation like adding a sample
or adding a data collection protocol involves communication with the server, and we have 2 places where the queue state is stored, in the client (tree) and in the server (internal queue representation). There is no guarantee the two are synchronized ; for example, if you stop the server and restart it, the UI still displays a queue but effectively it doesn't exist anymore in the server.

Maybe we should keep the queue state in client, and communicate with server only when queue is started (or while queue is running). 

What do you think ?

**Comment by meguiraun** [comment]
The PR should fix the missing fields, sorry.

The problem is that if the client crashes the server would not know anything about the queue… so... the other way around.

Right now, whenever an element is added/removed to queue (client side) it is also added in the server queue, only if the call to the server is successful. So, we have both queues synchronized, but always assuming that the master queue is in the server. I think we should not add critical logic to the client. 

We want to save the session (which basically is the queue + etc), and that is something to do in the server scope. We talked (fredrik and I) about having a periodic ’save_queue_to_file’ in the server, so if the server crashes and the user needs to log in again the server can check if the user has already a queue and send to him.

Perhaps is is time for the next skype meeting and we can review where we are and discuss this issues? What do you think about doing it on Thursday/Friday? Anytime is fine for me.

cheers,

mikel

**Comment by mguijarr** [comment]
Yes it would be great to have a chat session altogether, Friday would be ok for me. At 10:00 in the morning ? Tell me if it works for you.

I'm happy you started to think about the Session. It is indeed an important issue to solve.

About the Queue: I agree with you about the fact of having the queue stored on the server for the user session. But then we need to have the mecanism you're talking about to receive the queue
as soon as user logs in quite soon in order to be more comfortable during our own tests.

There is something we can probably optimize: instead of making a request for each sample that is added to the queue, maybe 1 request with all samples would speed things up ? I find it rather slow for the moment. What do you think ?

I am going to try to show data collection protocols associated with samples within sample cards in the Grid using your latest PR maybe this afternoon.

**Comment by mguijarr** [comment]
With latest PR #89, I think the only missing feature is the "Manually mounted" one. Will work on this in the next days or in January.

**Comment by mguijarr** [comment]
PR #91 adds the missing Manually mounted feature. Feel free to reopen if necessary, I close this one for now.
