### ISSUE TITLE
porposal_list not defined 

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#584]
Hi,

The login routine is giving me some errors here it seems like proposal_list is not defined
the first time loginInfo is called so we get an attribute error.

It seems like the proposal_list is also attached on the fly to the mxcube session, which is part of the problem.
It should either be defined on the Session hardware object directly or perhaps in the flask session.

Marcus

**Comment by meguiraun** [comment]
ok, gona have a look

**Comment by meguiraun** [comment]
https://github.com/mxcube/mxcube3/pull/587 solves the issue (without moving the dict to somewhere else)

**Comment by marcus-oscarsson** [comment]
Sorry for being persistent but is still get this AttributeError, not urgent to fix, but if you have the time please take a look.

You get it when you for instance kill the server, but stay logged in, then restart the server and refresh the page.

Cheers,
Marcus

**Comment by meguiraun** [comment]
see #608

**Comment by mguijarr** [comment]
Seems like it is fixed
