### ISSUE TITLE
Path, filename and run number

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#585]
Hi,

The filename, run number and image type (extension) should be given by the server

- The filename should be generated either completely or partly (by means of a template or similar) on the server

- The run number needs to be handled according to schema that is well defined and at least (if not entirely
managed by the server ) be initialized by the server.

- The file extension is closely coupled with the detector used and should be set once per session.

Marcus

**Comment by meguiraun** [comment]
file extension done by https://github.com/mxcube/mxcube3/pull/545, or you mean another thing?

**Comment by marcus-oscarsson** [comment]
But its not really the case, there are several places on the client where the distinction is made between h5 and cbf. Furthermore, if its h5 the suffix is changed to _master.h5. The resulting file will then be <filename>._master.h5. The suffix we use on the client should simply be the suffix given by the server nothing more nothing less. Actually we might not even need to pass the suffix to the client depending on how the filename is handled.

We need, in my opinion, to develop a better solution for the filename and then we will see how the suffix is passed.

**Comment by marcus-oscarsson** [comment]
Solved by #591
