### ISSUE TITLE
Grid - Cant draw grid when we have grid with results

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#658]
Cant draw a new grid when a grid with results already exists, some issue with result data

**Comment by meguiraun** [comment]
this is weird...

I tested it, I draw a grid and then I mock the results. And repeat for G2 and G3. there was a small (3 characters...) bug, pr coming

![image](https://user-images.githubusercontent.com/12758327/32318693-48395c66-bfb8-11e7-8483-9ee281c469bb.png)

**Comment by marcus-oscarsson** [comment]
Okey, all done. Great !

I have a small fix to add, we sometimes needed to delete a grid two times for it to be deleted

Marcus
