### ISSUE TITLE
Characterisation - auto add diffraction plan

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#664]
- The auto add option is not always taken into account
 - Refresh is needed for diffraction to be added to task, when auto add is false
 - Cant add resulting diffraction plan, something with associated shape ID

**Comment by meguiraun** [comment]
see PR #675

**Comment by marcus-oscarsson** [comment]
Thanks, all fixed !

**Comment by meguiraun** [comment]
great!

**Comment by marcus-oscarsson** [comment]
Alltough could you test it try with the built version to see if you have some issues. I got some issues when i used the build

**Comment by meguiraun** [comment]
ok, I will test
