### ISSUE TITLE
Web version installation instructions incomplete

### ISSUE THREAD

**Issue by niehsgst** [mxcube/mxcube3#718]
Referenced page: https://github.com/mxcube/mxcube3/wiki/How-to:-Installation
Following web version installation instructions on fresh Centos 7.3 VM; the line below indicates that at the completion of these steps, mxCuBE should be prepped to login (bypassing login "since we are using mockups"):
"Since we are using mockups you can type whatever you want in the user&password (but at least one char)."

However, connecting to mxCuBE server on port 8090 and attempting to login generates message "Login failed" on webpage; mxcube log reports "|HWR |ERROR | [LIMS]  Could not login to LIMS".

The source has not been touched at all so aside from performing 'yum install' a number of times to install the required packages, 'npm install', etc. according to the instructions, no other changes have been made to either the system or the mxCuBE files.

**Comment by mguijarr** [comment]
In fact the mockup LIMS connection module changed a few months ago, user for test login is `idtest000` ; password can be anything except the word `wrong` that is used to simulate a wrong password.
I updated the wiki - thanks for the report.
