### ISSUE TITLE
HardwareObject loses connection

### ISSUE THREAD

**Issue by robertoborghes** [mxcube/mxcube3#749]
Here at Elettra we've faced a strange problem with the HardwareObject that switches on/off the BackLight and FrontLight of the MD2 diffractometer. It worked without problems on a CentOS7 at the beamline (real computer), but last week we had to install another mxcube3 instance for development purposes. The devel installation works on a CentOS7 virtual machine, we've cloned from github mxcube3 and we've reused the customized HardwareObjects tested at the beamline.
Within this installation the web interface was not reacting to the state of the Backlight switch. After a lot of debug we've found a solution, but I admit that it's not clear to me why it works...

The problem is related to the script mxcube3/routes/SampleCentring.py when the signal 'actuatorStateChanged' is connected to the slot 'state_cb':

            motor_sw_hwobj = dm.getObjectByRole(motor + 'Switch')
            motor_sw_hwobj.connect(motor_sw_hwobj, 'actuatorStateChanged', state_cb)

This connection works the first time, but afterwards it is somehow "lost". It took really a lot of time (and a little bit of luck) to find a solution. We overload ed the 'connect' function inside the HardwareObject by adding this code:

    def connect(self, sender, signal, slot=None):
        # RB; really really strange: it seems that the default connection is
        # lost after first emit, by adding this function it works... MAH!!!
        self.slot = slot
        return Device.connect(self, sender, signal, slot)

For unknown reasons this solution solves the problem but if you remove the line self.slot = slot, the connection is lost again.
Here is the list of libraries installed on both machines:
     gevent (1.1.2)
     gevent-websocket (0.10.1)
     Flask (0.12.2)
     Flask-Session (0.3.1)
     Flask-SocketIO (2.8.0)
     Louie (1.1)

**Comment by marcus-oscarsson** [comment]
Hi

That seems really strange indeed, I think it might have to do with garbage collection or that the state_cb
is overwritten. The assignment you do in your fix some how points a bit towards that it might be garbage collection related.

My suspicion is that state_cb for some reason gets garbage collected, or maybe re-assigned somewhere ?. The line 
    
     setattr(dm, "_%s_state_callback" % motor, state_cb)

stores the state_cb on the diffractometer object to prevent it from being garbage collected. However something might be re-initializing the diffractometer or something else is maybe overwriting "_%s_state_callback" ?

You could maybe check if the method "_%s_state_callback" exists on the diffractometer object when you perform the in or out action. ?

What do you think about that ?

Kinds regards,
Marcus

**Comment by rhfogh** [comment]
Just a totally uninformed reaction:
Why are you passing in 'motor="zoom"'
when the motor parameter is hardly (soon: not) used, and you have hardcoded 'zoom' everywhere? Required by the framework?

**Comment by meguiraun** [comment]
@robertoborghes, good catch. Shame on me... In fact it is not working in our beamline either...

Could you make a PR with the fix that you suggest?

@rhfogh, nothing in particular, consequences of copy&paste from lines above

**Comment by marcus-oscarsson** [comment]
Hi,

I see, thanks for the good detective work :+1: . You are right that, 

```
 setattr(dm, "_%s_state_callback" % motor, zoom_state_cb)
```

Is wrong, I suspect that a recent update to master must have changes this somehow, and that's why you did not see it before.

```
setattr(dm, "_zoom_state_callback", zoom_state_cb)
```

Seems much better, and we can also remove the keyword argument motor="zoom".

Let me know if you are going to do a PR for this, Id like to include this fix in the beta2 release. Ill try to rebase what we are using on ID29 with the lastest changes on master to create the beta2 release tomorrow. Ill push it after I have done enough testing to make sure nothing was broken by the rebase.

Cheers and thanks,
Marcus

**Comment by robertoborghes** [comment]
Hi,
since I'm not really familiar with git it would be faster if you could do a PR (now I know what it means) for this. Please let me know if it is OK for you or if you want me to proceed.
Ciao,
Roberto

**Comment by marcus-oscarsson** [comment]
Sure no problem, I can do it for you if you like. 

If you feel like playing around you can give it a try otherwise ill do it, don't worry.

Ciao,
Marcus

**Comment by robertoborghes** [comment]
Sorry,
doing a git diff I've noticed that I had to modify another code line in the sampe script mxcube3/routes/SampleCentring.py. In order to see a JPEG streaming I had to modify line 196 from:

yield 'Content-type: image/jpg\n\n' + SAMPLE_IMAGE + "\n--!>"

to 

yield (b'--!>\r\nContent-Type: image/jpeg\r\n\r\n' + SAMPLE_IMAGE + b'\r\n')

It was a problem only for us?
Thanks,
Roberto

**Comment by marcus-oscarsson** [comment]
Hm, 

Thats funny, image/jpeg is the correct mime type but image/jpg should work as well. It have always worked for us, all tough we are using the mpeg streaming option on the beamline. But the mockup version and MAX IV uses streaming jpeg images so it should work with image/jpg.

Ill change it image/jpeg because I think that's actually the correct mime type.

Thanks again,
Marcus

**Comment by robertoborghes** [comment]
Currently we're using fireFox fo Ubuntu 58.0.2 (64-bit).
In our case I'm not sure that the problem resides in the mime type, I would bet on the terminator '\r\n'...

Roberto

**Comment by marcus-oscarsson** [comment]
Oh, what version of Python are you using ?

**Comment by robertoborghes** [comment]
Python 2.7.5

**Comment by marcus-oscarsson** [comment]
If you have the time, can you verify that its the \r\n that make the difference ?

**Comment by robertoborghes** [comment]
I managed to perform some tests (Firefox and Chrome on Ubuntu 16.04) and our hypothesis were wrong.
GitHub version does not work for me:
 - yield 'Content-type: image/jpg\n\n' + SAMPLE_IMAGE + "\n--!>"

This version (even without \r\n) works for me:
 - yield '--!>\nContent-type: image/jpg\n\n' + SAMPLE_IMAGE

The key seems to be the position of the '--!>'  token...

**Comment by marcus-oscarsson** [comment]
@meguiraun do you mind of we change to 

```
yield '--!>\nContent-type: image/jpg\n\n' + SAMPLE_IMAGE
```

Marcus

**Comment by meguiraun** [comment]
I cannot test in real environment now, but it seems there is no difference with mockups. So go ahead.
