### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#8]
Login into ISPyB and retrieve the sample list and the relevant data for all the samples involved in the experiment. In the beginning it can be a single proposal with a single crystal defined in the database. The ISPyB integration is already done in existing HardwareObjects therefore it should not involve too much extra work.

**Comment by mguijarr** [comment]
This is solved for a big part with PR #77 (already merged). I propose to close this one, and to create another one for the Login page. Then if we miss something we can re-open this one or make another issue... ?

**Comment by meguiraun** [comment]
let this opened until Friday, Jie was doing some fixes on this for our login servers.

**Comment by JieNanMAXIV** [comment]
So far, I only did change on the MaxLabISPyBClient2.py and mxcube3. See the PR for more details, and we can review it quickly this Friday.

**Comment by mguijarr** [comment]
Merged PR #83 this morning. I think we can close this issue. However I am going to open another one to have the Login page done.
