### ISSUE TITLE
Create AbstractMachineInfo

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#835]
Use MachineInfo as inspiration for AbstractMachineInfo

Add to the already existing methods:
- get_undulator_gaps()
- get_machine_current()
- get_machine_state_text()

Finally make sure that MachineInfo inherits AbstractMachineInfo

**Comment by IvarsKarpics** [comment]
This issue should be in HardwareRepository

**Comment by marcus-oscarsson** [comment]
Yes, I noticed moving them now
