### ISSUE TITLE
Rename AbstractMicroscope to AbstractSampleView

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#836]
Rename AbstractMicroscope to AbstractSampleView and Microscope to SampleView

AbstractSampleView derive from HardwareObject (As all Abstract objects)
Add the attributes:
- graphics
- shapes
- zoom
- front_light
- back_light 
- camera
- get_snapshot(overlays=boolean)
- ...

**Comment by IvarsKarpics** [comment]
This issue should be in HardwareRepository
