### ISSUE TITLE
Adding many samples to the Sample Queue is slow

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#84]
When adding a lot of samples from the Sample Grid (e.g. 50 samples or more), the UI sends a
request per sample and waits for server reply before actually adding the sample to the queue, which gives impression of a slow UI - we need to improve that, there are 2 ways (can be combined...):

- doing optimistic rendering, as Frederik proposed : updating the queue before having the answer from server, then displaying an error message if an answer is bad
- changing API to be able to send all samples in one go

This is not a first priority task so the milestone is pushed to March.

**Comment by marcus-oscarsson** [comment]
This is already partially solved by #323 where we don't use jsonpickle to store the queue, so the time for the request is smaller.

Its completely solved by #325 where there is no request done until the queue runs.

Ill close this even if those PRs are not yet accepted.
