### ISSUE TITLE
Populate RobotAction

### ISSUE THREAD

**Issue by stufisher** [mxcube/mxcube3#842]
Could mxcube please populate RobotAction when a sample is mounted. There is already a webservice to do this in ISPyB:

https://github.com/ispyb/ISPyB/blob/master/ispyb-ws/src/main/java/ispyb/ws/soap/mx/ToolsForCollectionWebService.java#L1752

Mxcube needs to populate the start and end time then load times can be reported on

**Comment by marcus-oscarsson** [comment]
This issue, should be made for HardwareRepository as its not a MXCuBE3 specific issues so I'm going to close it and reopen it. Ill double check with Alejandro to make sure that there is nothing already in place ...

Marcus
