### ISSUE TITLE
Which Python versions are supported?

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcube3#945]
In the newest merge, I notice :

mxcube3/conda-environment.yml

dependencies:
  - python >3.8,<3.11

mxcube3/pyproject.toml

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

mxcubecore/pyproject.toml

[tool.poetry.dependencies]
python = ">=3.7,<3.11"

Near as I can see, the lowest allowed Python version is either 3.7, 3.8, or 3.9, depending on where you look. If the conda-environment overrides the toml file, the lowest version you can actually use is 3.9. 

Before I start experimenting with getting these conda environments set up in a system that works for me where the repository files do not live in conda - could someone tell me how this is supposed to work - and fix anything that needs fixing?

Yours,
Rasmus

**Comment by marcus-oscarsson** [comment]
Ah yes, thanks for noticing that. I made a mistake in the conda-environemnt.yml it should be >=

The conda-environment.yml simply sets up your basic environment, you can ignore it if you are not using conda.

However you need to make sure that you have a Python = ">=3.8,<3.11" openldap and poetry installed in whatever environment you are using. I would strongly recommend conda or similar for this.

That mxcubecore supports python 3.7 is not really a problem, the python version in your current environment will be used for installing mxcubecore and that should then be between 3.7 and 3.11.

Python 3.7 go out of support during 2023 so its better that we start to already move away from it. We should do the same for mxcubecore as long as it does not pose any problem for the Qt UI.
