### ISSUE TITLE
Add python-ldap to conda-environment.yml?

### ISSUE THREAD

**Issue by beenje** [mxcube/mxcube3#954]
`python-ldap` is defined as dependency in mxcubecore https://github.com/mxcube/mxcubecore/blob/624f110c852902f73bb105c34e7c4e9fa4d8f30f/pyproject.toml#L48 but there is no wheel on pypi (https://pypi.org/project/python-ldap/#files), only sdist :-(

It currently requires gcc to install via pip, which is annoying. Would it be possible to add it to the `conda-environment.yml`? 

My understanding is that the new conda environment should be kept to the minimum and for non python packages only.
Which I think makes sense to avoid conflicts between conda/pip and to avoid having to maintain versions in different files.

But in practice there are still some python packages difficult to install with pip... Pytango is another good example (it will change with 9.4.0!).

What is the current suggestion for those packages?

PS: another minor issue is that python-ldap 3.4.3 isn't available yet on conda-forge. Latest version is 3.4.0.
There is a [PR](https://github.com/conda-forge/python-ldap-feedstock/pull/23) so it should soon be there.

**Comment by marcus-oscarsson** [comment]
Hm, you are right that the `python-ldap` package can create some trouble, especially if you don't have gcc. Out of curiosity how does it come that you don't have gcc ?

I would be fine with moving python-ldap to `conda-environment.yml`, especially since open-ldap is already there. The idea is otherwise to keep the `conda-environment.yml` as small as possible.

**Comment by beenje** [comment]
We deploy using Ansible and the role is tested in a docker container with a minimum set of packages installed.
We can add `gcc` to the required packages. I usually don't think it should be needed on a production server but I'm fine adding it if needed.

I think `python-ldap` could go with `openldap`. I'll let you decide how you prefer to maintain this.

Thanks!

**Comment by marcus-oscarsson** [comment]
Most of us have GCC even on our production servers, so its not really an issue for the majority of us if it comes down simply to not having GCC. I can understand the argument in an embedded environment (or perhaps simply out of principle) but its not really our case. 

As fore mentioned, I'm fine with moving `python-ldap` to `conda-environment.yml `. What I can suggest that one of you at MAXIV @meguiraun, @meghdadyazdi make a PR with the suggested change ?

**Comment by beenje** [comment]
With the 2 MRs referenced above, I think this can be closed.
